== API ==

[caption="Rule {counter:rule-number}: "]
.API
==========================
An API bundles a set of resources which are _functionally related_ and form an autonomous _unit of business logic_.
==========================

Compare an API to the concept of http://serviceorientation.com/soaglossary/service[_Services_ in service-orientation^] or the concept of http://martinfowler.com/bliki/BoundedContext.html[_Bounded Contexts_ in Domain-Driven Development^].


[caption="Rule {counter:rule-number}: "]
.API format
==========================

*URI =* `"https://"` [green]#_host_# `"/REST"` [green]#_apiName_# `"/v"` [green]#_majorVersion_# `"/"` [green]#_resources_#

[gray]#_example:_ \https://services.socialsecurity.be/REST/employerProfile/v1/profiles#

`"https://"`:: Services are at least secured on transport level using a one-way TLS connection. The implicit port is 443.
host:: Hostname is determined by the http://integrationsoa/site_nl/infrastructure/social_security.html[environment^] where the service is deployed. Currently, RESTful services are deployed on the same SOA platform as SOAP-based services.
`"/REST"`:: Temporal prefix to discriminate between SOAP and RESTful services.
apiName:: Name of the API that groups a functional consistent set of resources. The API name consists of one or multiple _path segments_ written in lowerCamelCase [gray]#(example: /referenceData/geography)#.
majorVersion:: Major version numbers are numeric and start at 1.
resources:: All path segments identifying the actual resources.


==========================

