[[api-specs]]
== API specifications

[.rule, caption="Rule {counter:rule-number}: "]
.API contract-first approach
====
The contract-first principle SHOULD be followed when developing an API.
In this approach, the specifications of the REST API are created first and not generated from the code.

A code-first approach may sometimes be necessary however, as current state of technology does not always fully support contract-first development.
In this case, special attention should be given that the API specifications remain stable and loosely coupled to the API implementation technology.
====

[[openapi]]
=== OpenAPI (Swagger)

OpenAPI is the dominating standard for API documentation, having gained wide industry support.
It is based on http://swagger.io/[Swagger^], which has been standardized as https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md[OpenAPI 2.0].

[.rule, caption="Rule {counter:rule-number}: "]
.OpenAPI
====
Specifications of the API SHOULD be provided using https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md[*OpenAPI 2.0*] (aka Swagger) or https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md[*OpenAPI 3.0*].
OpenAPI uses the https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject[OpenAPI Schema Object] to describe the JSON representation of resources, which is a variant of https://json-schema.org/specification-links.html#draft-4[*JSON Schema*], with some significant incompatibilities.
====

The OpenAPI 2.0 standard specifies how to define https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject[Schema Objects]
and https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types[Data Types] and the differences with the JSON Schema standard.

[NOTE]
OpenAPI 3.0 fixes some shortcomings in OpenAPI 2.0.
However, this guide has not been updated yet for OpenAPI 3.0 but most is still applicable.

You can visualize OpenAPI files using tools like https://swagger.io/swagger-ui/[Swagger UI^], https://github.com/moon0326/swagger-ui-watcher[Swagger UI Watcher^] or https://senya.io[Senya^].

[.rule, caption="Rule {counter:rule-number}: "]
.Additional documentation
====
Any additional documentation SHOULD be linked from the API's OpenAPI definition using the `externalDocs` property.
====

[.rule, caption="Rule {counter:rule-number}: "]
.Use YAML format for OpenAPI
====
OpenAPI files SHOULD be made available in YAML format, and OPTIONALLY in JSON format as well.

YAML is a superset of JSON which allows a simpler notation, and also allows comments.
According to usage, a conversion step to JSON might be necessary considering limitations of tools.
====

[.rule, caption="Rule {counter:rule-number}: "]
.Use tags to group operations
====
When an API has many operations, use https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#tagObject[tags] to group them together.
This will make the visual representation (SwaggerUI) more readable.
====

[[doc-resource,doc resource]]
[.rule, caption="Rule {counter:rule-number}: "]
.`doc` and `refData` resources
====
The OpenAPI specification file and other API documentation SHOULD be placed under a special `doc` resource under the API root location.

The swagger specification file is, https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#file-structure[by convention], named `swagger.json` or `swagger.yaml`.
Root OpenAPI 3.0 documents SHOULD be named `openapi.json` or `openapi.yaml`, as specified in the https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#document-structure[OpenAPI 3.0 specification].

Resources representing reference data (code lists) specific to an API SHOULD be placed under a `refData` resource.
As reference data is typically static, consider supporting <<Caching>> headers for these resources.
====

Note that these are exceptions to the rule that API resource URLs shouldn't have a file extension.

.`doc` and `refData` resources
====
```
 /doc
     /swagger.json
     /swagger.yaml
     /<optional other documentation>
 /refData
     /<list1OfCodes>
        /<code1>
        /<code2>
        /...
     /<list2OfCodes>
        /...
 /<resource1>
     /...
 /<resource2>
     /...
 ...
```
====

[[default-values,default values]]
[.rule, caption="Rule {counter:rule-number}: "]
.`default` values
====
Absent optional properties in a request are set by the API provider to their `default` value if one is specified in the OpenAPI specification.
====

[.rule, caption="Rule {counter:rule-number}: "]
.Add examples in OpenAPI
====
Add example response values to the OpenAPI specification under the `examples` property.
====

```YAML
  /enterprises/{enterpriseNumber}:
    get:
      operationId: getEnterprise
      parameters:
      - in: path
        name: enterpriseNumber
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            $ref: '#/definitions/Enterprise'
          examples:
            application/json:
              {
                "name": "Belgacom",
                "enterpriseNumber": "0202239951"
              }
```

WARNING: OpenAPI 2.0 only allows a single example per media type under `examples`.
  Any additional examples should be put in external documentation.

[.rule, caption="Rule {counter:rule-number}: "]
.Reusable OpenAPI definitions
====
Instead of specifying everything directly in the `swagger.yaml` file of an API, OpenAPI allows to reference data types and other definitions from other reusable files.
These files SHOULD follow the Swagger/OpenAPI file format as well and may include data type definitions, but also parameter, path items and response objects.

To work around limitations of certain tools, a conversion step to inline the definitions into the `swagger.yaml` file may be necessary.

Duplication of types in multiple APIs SHOULD be avoided. Rather, put the type in a reusable OpenAPI file.
Files reusable from multiple APIs SHOULD be organized in this structure:
```
<domain>/<version>/<domain-version>.yaml
<domain>/<subdomain>/<version>/<domain-subdomain-version>.yaml
```

Definitions SHOULD be grouped per (sub)domain in a file.
Each file has its own lifecycle, with a major version number in it's directory and file name, that is increased when backwards compatibility is broken.
This version, with optionally a minor and patch version added to it, MUST be specified in the `info` section in the swagger file as well.
====

While it is not strictly necessary for external definitions to be put in a valid OpenAPI 2.0 file, doing so makes it possible to use standard OpenAPI/Swagger tooling on them.

.Reusable OpenAPI file
====
./person/identifier/v1/person-identifier-v1.yaml
```YAML
swagger: "2.0"
info:
  title: data types for person identifiers
  version: v1beta
paths: {} # empty paths property required to be a valid OpenAPI file
definitions:
  Ssin:
    description: "Social Security Identification Number issued by the National Register or CBSS"
    type: string
    pattern: \d{11}
```

A type can be referenced from another OpenAPI file:
```YAML
"$ref": "./person/identifier/v1/person-identifier-v1.yaml#/definitions/Ssin"
```
====

[[belgif-openapi-types, Common OpenAPI definitions]]
[.rule, caption="Rule {counter:rule-number}: "]
.Common definitions for Belgian government institutions
====
Common definitions for use by Belgian government institutions are available in the https://github.com/belgif?q=openapi&type=&language=[openapi-* GitHub repositories], organized per domain.
Types in these schemas SHOULD be used instead of defining your own variants.

The technical types referenced in this style guide are available in the https://github.com/belgif/openapi-common[openapi-common] and https://github.com/belgif/openapi-problem[openapi-problem] repositories.
Other types for business concepts commonly used by Belgian government institutions are available in other repositories.
====

The OpenAPI files will in the future (WIP) be released in zip archives and via a Maven repository.
In addition, they will also be made available on https URLs both in YAML and JSON format through content negotiation (see <<Media Types>>), with YAML being the default format.

=== JSON data types

[.rule, caption="Rule {counter:rule-number}: "]
.Naming of data types
====
Data type names SHOULD be defined in American English and use _UpperCamelCase_ notation.
For abbreviations as well, all letters except the first one should be lowercased.

Do not use underscores (_), hyphens (-) or dots (.) in a data type name, nor use a digit as first letter.

Overly generic terms like `info(rmation)` and `data` SHOULD NOT be used as data type name or part of it.

A data type name SHOULD refer to the business meaning rather than how it is defined.
====

|===
|KO|OK

|SSIN | Ssin
|CustomerInformation | Customer
|LanguageEnumeration | Language
|===

[.rule, caption="Rule {counter:rule-number}: "]
.Data type description
====
The `description` property MAY provide a textual description of a JSON data type.
The `title` property MUST NOT be used because it is hides the actual data type name in visualization tools like Swagger UI.
====

|===
|KO|OK

a|
```YAML
Pet:
  title: a pet in the pet store
  type: object
```

a|
```YAML
Pet:
  description: a pet in the pet store
  type: object
```

|===


`additionalProperties` can be used to put restrictions on other properties of a JSON object than those specified in the schema.

[.rule, caption="Rule {counter:rule-number}: "]
.additionalProperties
====
`additionalProperties` SHOULD be used exclusively to describe an object representing a map of key-value pairs.
The keys of such maps don't need to respect the naming rules for JSON properties (lowerCamelCase and English).
====

An example is the description a map of `embedded` resources, as described in <<Embedded resources>>.
Other uses of `additionalProperties` than for maps are to be avoided, in order to support schema evolution.

[.rule, caption="Rule {counter:rule-number}: "]
.readOnly properties
====
Properties SHOULD  be declared readOnly when appropriate.

Properties can be declared `readOnly: true`.
This means that it MAY be sent as part of a response but MUST NOT be sent as part of the request.
Properties marked as readOnly being true SHOULD NOT be in the required list of the defined schema.

Examples are properties that are computed from other properties, or that represent a volatile state of a resource.
====

[.rule, caption="Rule {counter:rule-number}: "]
.Enum values
====
A fixed list of possible values of a property can be specified using `enum`.
However, this may make it harder to change the list of possible values, as client applications will often depend on the specified list e.g. by using code generation.

`enum` SHOULD only be used when the list of values is unlikely to change or when changing it has a big impact on clients of the API.

Enumerated string values SHOULD be declared in lowerCamelCase, just as property names.
====

.Enum declaration
====
```YAML
state:
  type: string
  enum:
  - processing
  - failed
  - done
```
====

[.rule, caption="Rule {counter:rule-number}: "]
.String and integer types
====
When defining the type for a property representing a numerical code or identifier:

* if the values constitute a list of sequentially generated codes (e.g. gender ISO code), `type: integer` SHOULD be used. It is RECOMMENDED to further restrict the format of the type (e.g. `format: int32`).
* if the values are of fixed length or not sequentially generated, `type: string` SHOULD be used (e.g. Ssin, EnterpriseNumber). This avoids leading zeros to be hidden.

When using a string data type, each code SHOULD have a unique representation, e.g. don't allow representations both with and without a leading zeros or spaces for a single code.
If possible, specify a `pattern` with a regular expression restricting the allowed representations.
====

[[openapi-tools]]
=== Tools

Following tools can be used to edit OpenAPI files

[options="header"]
|===
|Name|Link| Description
|KaiZen OpenAPI editor | https://github.com/RepreZen/KaiZen-OpenAPI-Editor | Open Source Eclipse plugin. Text only editor.
|Swagger UI | https://swagger.io/swagger-ui/ | Browser application. Graphical and text view of Swagger files. Does not support references to external files.
|Swagger UI watcher | https://github.com/moon0326/swagger-ui-watcher | Swagger UI with multi-file support. Only supports viewing. View is refreshed on each file change.
|Zalando's Swagger plugin | https://github.com/zalando/intellij-swagger | Plugin for IntelliJ. Text-only Swagger editor
|RepreZen | https://www.reprezen.com/ | Commercial editor based on KaiZen. Graphical and text view.
|Senya Editor | https://senya.io | Commercial IntelliJ IDEA plugin. Graphical and text view.
|Stoplight Studio | https://stoplight.io/studio/ | Open Source editor with graphical and text view, both web based or as desktop application. Supports validation of API style guides (https://stoplight.io/open-source/spectral[Spectral]).
|===

Following tools can be used to generate server stubs and API client libraries from OpenAPI specification files.

[options="header"]
|===
|Name|Link| Comments
|openapi-generator| https://openapi-generator.tech/ | Started as fork of swagger-codegen.
|swagger-codegen| https://github.com/swagger-api/swagger-codegen|
|===

=== References

[options="header"]
|===
|Name|Link
|OpenAPI 2.0 specification| http://spec.openapis.org/oas/v2.0.html
|OpenAPI 3.0 specification| http://spec.openapis.org/oas/v3.0.3.html
|Swagger | https://swagger.io/docs/specification/2-0/basic-structure/
|===
