== API specifications

[CAUTION]
.JSON or YAML
====
It is still under discussion whether to use JSON or YAML for Swagger definitions and JSON schemas. See issue #6.
====

=== Swagger

All RESTful services should be documented using the http://swagger.io/[Swagger^] standard. The Swagger specification of the service is exposed as an API resource with URI `/api/doc/swagger.json` (see <<api-resource>>).

[CAUTION]
.Open issue: URL of swagger file still under discussion
====
Cfr discussion of the API resource
====

You can visualize the Swagger description using the https://swagger.io/swagger-ui/[Swagger UI^]. The `url` query parameter specifies to Swagger file to load.

=== JSON Schema

We favor a contract-first design approach where JSON resource respresentations are described in formal schemas. **JSON schema draft 04** is the standard used and is also reused in your Swagger API specification.

[CAUTION]
.Open issue: location of common JSON schemas
====
Under discussion: guidelines how to publish JSON schemas that are used in multiple APIs. See issue #7.
====

[CAUTION]
.Open issue: Recommendation whether to use nullable: true
====
Guideline depends on output of absent JSON values discussion #4
====

[caption="Rule {counter:rule-number}: "]
.use of "additionalProperties" is NOT RECOMMENDED
==========================
"additionalProperties" can be used to put restrictions on other properties of a JSON object than those specified in the schema.

Schemas should avoid using additionalProperties declarations, in order to support schema evolution.
==========================

**Useful references**

[options="header"]
|===
|Name|Link
|JSON Schema Official Site|http://json-schema.org[http://json-schema.org^]
|JSON Schema Core specification|http://json-schema.org/latest/json-schema-core.html[http://json-schema.org/latest/json-schema-core^]
|JSON Schema Validation specification|http://json-schema.org/latest/json-schema-validation.html[http://json-schema.org/latest/json-schema-validation^]
|JSON Schema User guide|http://spacetelescope.github.io/understanding-json-schema[http://spacetelescope.github.io/understanding-json-schema^]
|XMLSpy 2017|The XML editor now fully supports JSON and JSON schemas
|JSON Schema generator based on sample JSON message|http://jsonschema.net​
|Mock JSON message generator | http://schematic-ipsum.herokuapp.com
|===

'''

JSON schema allows to add user-defined properties. This sections lists the properties which are not default in the specification.