== API specifications

[.rule, caption="Rule {counter:rule-number}: "]
.API contract-first approach
====
The contract-first principle SHOULD be followed when developing an API.
In this approach, the specifications of the REST API are created first and not generated from the code.

A code-first approach may sometimes be necessary however, as current state of technology does not always fully support contract-first development.
In this case, special attention should be given that the API specifications remain stable and loosely coupled to the API implementation technology.
====

[.rule, caption="Rule {counter:rule-number}: "]
.Use of YAML format in OpenAPI and JSON Schema
====
OpenAPI and JSON Schema files SHOULD be made available in YAML format, and OPTIONALLY in JSON format as well.

YAML is a superset of JSON which allows a simpler notation, and also allows comments.
According to usage, a conversion step to JSON might be necessary considering limitations of tools.
====

[[doc-resource,doc resource]]
[.rule, caption="Rule {counter:rule-number}: "]
.`doc` resource
====
The OpenAPI specification file and other API documentation SHOULD be placed under a special `doc` resource under the API root location.

The swagger specification file is, https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#file-structure[by convention], named `swagger.json` or `swagger.yaml`.

Root OpenAPI 3.0 documents SHOULD be named `openapi.json` or `openapi.yaml`, as specified in the https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#document-structure[OpenAPI 3.0 specification].
====

Note that these are exceptions to the rule that API resource URLs shouldn't have a file extension.

.`doc` resource
====
```
 /doc
     /swagger.json
     /swagger.yaml
     /<optional other documentation>
 /<resource1>
     /...
 /<resource2>
     /...
 ...
```
====

=== OpenAPI (Swagger)

OpenAPI is the dominating standard for API documentation, having gained wide industry support.

[.rule, caption="Rule {counter:rule-number}: "]
.OpenAPI 2.0 (Swagger)
====
Specifications of the API SHOULD be provided using OpenAPI 2.0 (aka Swagger).
====

http://swagger.io/[Swagger^] has been standardized as the https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md[OpenAPI standard].
The OpenAPI 3.0 standard should not be used yet for now, as tooling and library support is not yet sufficiently up to date with this version.

You can visualize the Swagger description using the https://swagger.io/swagger-ui/[Swagger UI^]. The `url` query parameter specifies to Swagger file to load.

[.rule, caption="Rule {counter:rule-number}: "]
.Additional documentation
====
Any additional documentation SHOULD be linked from the API's OpenAPI definition using the `externalDocs` property.
====

=== JSON Schema

OpenAPI uses JSON schemas to describe JSON resources.

[.rule, caption="Rule {counter:rule-number}: "]
.JSON Schema
====
JSON Schema MUST be used to describe JSON resources.

The version of JSON Schema to be used is the variant of **JSON schema draft 04** defined in the OpenAPI 2.0 specification as the https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject[OpenAPI Schema Object].

JSON schemas can be included directly in the `swagger.json` file or in separate files referenced from the OpenAPI description.
According to usage, a conversion step to inline the definitions into the OpenAPI file might be necessary considering limitations of tools.

Duplication of types in multiple APIs SHOULD be avoided. Rather, put the type in a reusable JSON Schema.

A JSON Schema file SHOULD contain a single root type.
Any dependent types used by this root type MUST be added under a `definitions` property.
The file name SHOULD correspond to the name of the data type.

A JSON Schema file SHOULD be versioned with at least a major version number, that is increased when backwards compatibility is broken.
Multiple JSON Schema files defining types in the same domain may be versioned as a whole.
If the schema's `id` is specified, it MUST contain the major version number.
====

[.rule, caption="Rule {counter:rule-number}: "]
.Common schema types for Belgian government institutions
====
Common JSON schemas for use by Belgian government institutions are published on https://www.gcloud.belgium.be/rest/schemas/.
Types in these schemas SHOULD be used instead of defining your own variants.

(TODO: this path is not yet navigable).

Each subpath defines a domain that is versioned as a whole.
The technical types referenced in this style guide are available in the `common` subpath.
Other types for business concepts commonly used by Belgian government institutions are added in other subpaths.

The JSON schema files will be made available both in YAML and JSON format through content negotiation (see <<Media Types>>), with YAML being the default format.
(TODO: still to be done; only available as <type>.yaml currently)
====

[.rule, caption="Rule {counter:rule-number}: "]
.JSON Schema data type names
====
JSON Schema data type names SHOULD be defined in American English and use _UpperCamelCase_ notation.
For abbreviations as well, all letters except the first one should be lowercased.
====

.JSON Schema
====

The two types below are defined in the first version of the "person identifier" domain.

.Ssin.yaml
```YAML
id: http://example.org/person/identifier/v1/Ssin
"$schema": http://json-schema.org/draft-04/schema#
description: "Social Security Identification Number issued by the National Register or CBSS"
type: string
pattern: \d{11}
```

.Nrn.yaml
```YAML
id: http://example.org/person/identifier/v1/Nrn
"$schema": http://json-schema.org/draft-04/schema#
description: "National Register Number: identification number of a natural person issued by the National Register"
type: string
pattern: \d{11}
```

A type can be referenced from an OpenAPI or JSON Schema document:
```YAML
"$ref": http://example.org/person/identifier/v1/Ssin
```
====

`additionalProperties` can be used to put restrictions on other properties of a JSON object than those specified in the schema.

[.rule, caption="Rule {counter:rule-number}: "]
.additionalProperties
====
`additionalProperties` SHOULD be used exclusively to describe an object representing a map of key-value pairs.
The keys of such maps don't need to respect the naming rules for JSON properties (lowerCamelCase and English).
====

An example is the description a map of `embedded` resources, as described in <<Embedded resources>>.
Other uses of `additionalProperties` than for maps are to be avoided, in order to support schema evolution.

[.rule, caption="Rule {counter:rule-number}: "]
.readOnly properties
====
Properties SHOULD  be declared readOnly when appropriate.

Properties can be declared `readOnly: true`.
This means that it MAY be sent as part of a response but MUST NOT be sent as part of the request.
Properties marked as readOnly being true SHOULD NOT be in the required list of the defined schema.

Examples are properties that are computed from other properties, or that represent a volatile state of a resource.
====

[.rule, caption="Rule {counter:rule-number}: "]
.Enum values
====
A fixed list of possible values of a property can be specified using `enum`.
However, this may make it harder to change the list of possible values, as client applications will often depend on the specified list e.g. by using code generation.

`enum` SHOULD only be used when the list of values is unlikely to change or when changing it has a big impact on clients of the API.

Enumerated string values SHOULD be declared in lowerCamelCase, just as property names.
====

.Enum declaration
====
```YAML
state:
  type: string
  enum:
  - processing
  - failed
  - done
```
====

[.rule, caption="Rule {counter:rule-number}: "]
.String and integer types
====
When defining the type for a property representing a numerical code or ID:

* if the values constitute a list of sequentially generated codes (e.g. gender ISO code), `type: integer` SHOULD be used. It is RECOMMENDED to further restrict the format of the type (e.g. `format: int32`).
* if the values are of fixed length or not sequentially generated, `type: string` SHOULD be used (e.g. Ssin, EnterpriseNumber). This avoids leading zeros to be hidden.
====

**Useful references**

[options="header"]
|===
|Name|Link
|JSON Schema Official Site|http://json-schema.org[http://json-schema.org^]
|JSON Schema Core specification|http://json-schema.org/latest/json-schema-core.html[http://json-schema.org/latest/json-schema-core^]
|JSON Schema Validation specification|http://json-schema.org/latest/json-schema-validation.html[http://json-schema.org/latest/json-schema-validation^]
|JSON Schema User guide|http://spacetelescope.github.io/understanding-json-schema[http://spacetelescope.github.io/understanding-json-schema^]
|XMLSpy|The XML editor now fully supports JSON and JSON schemas
|JSON Schema generator based on sample JSON message|http://jsonschema.net​
|Mock JSON message generator | http://schematic-ipsum.herokuapp.com
|===

'''
