== API specifications

[caption="Rule {counter:rule-number}: "]
.API contract-first approach
====
The contract-first principle SHOULD be followed when developing an API.
In this approach, the specifications of the REST API are created first and not generated from the code.

A code-first approach may sometimes be necessary however, as current state of technology does not always fully support contract-first development.
In this case, special attention should be given that the API specifications remain stable and loosely coupled to the API implementation technology.
====

[caption="Rule {counter:rule-number}: "]
.Use of YAML format in OpenAPI and JSON Schema
==========================
OpenAPI and JSON Schema files SHOULD use YAML format rather JSON.
YAML is a superset of JSON which allows a simpler notation, and also allows comments.
According to usage, a conversion step to JSON might be necessary considering limitations of tools.
==========================

[caption="Rule {counter:rule-number}: "]
.`doc` resource
==========================
The OpenAPI specification file and other API documentation SHOULD be placed under a special `doc` resource under the API root location.

The swagger specification file is, https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#file-structure[by convention], named `swagger.json` and/or` swagger.yaml`.
In OpenAPI 3.0, it is RECOMMENDED that the root OpenAPI document be named `openapi.json` or `openapi.yaml`.
Note that these are exceptions to the rule that API resource URLs shouldn't have a file extension.
==========================

.`doc` resource
====
```
 /doc
     /swagger.json
     /swagger.yaml
     /<optional other documentation>
 /<resource1>
     /...
 /<resource2>
     /...
 ...
```
====

=== OpenAPI

OpenAPI is the dominating standard for API documentation, having gained wide industry support.

[caption="Rule {counter:rule-number}: "]
.OpenAPI 2.0 (Swagger)
==========================
Specifications of the API SHOULD be provided using OpenAPI 2.0 (aka Swagger).

http://swagger.io/[Swagger^] has been standardized as the https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md[OpenAPI standard].
The OpenAPI 3.0 standard should not be used yet for now, as tooling and library support is not yet sufficiently up to date with this version.
==========================

You can visualize the Swagger description using the https://swagger.io/swagger-ui/[Swagger UI^]. The `url` query parameter specifies to Swagger file to load.

[caption="Rule {counter:rule-number}: "]
.Version of the API
==========================
The version of the API SHOULD be included in the `info` section of the OpenAPI definition.
==========================

Example:
[subs="normal"]
```YAML
swagger: 2.0
info:
  name: petshop
  description: API exposing my petshop's functionality
  version: 1.0.0
```

[caption="Rule {counter:rule-number}: "]
.Additional documentation
====
Any additional documentation SHOULD be linked from the API's OpenAPI definition.

It is recommended to add links in the OpenAPI definition using the 'externalDocs' property to any additional API documentation or user manual.
====

=== JSON Schema

OpenAPI uses JSON schemas to describe JSON resources.
JSON schemas can be included directly in the `swagger.json` file or in separate files referenced from the OpenAPI description.

[caption="Rule {counter:rule-number}: "]
.JSON Schema
==========================
JSON Schema MUST be used to describe JSON resources.

The version of JSON Schema to be used is the variant of **JSON schema draft 04** defined in the OpenAPI 2.0 specification as https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject[OpenAPI Schema Object].
==========================

[caption="Rule {counter:rule-number}: "]
.JSON Schema data type names
==========================
JSON Schema data type names SHOULD be defined in English and use _UpperCamelCase_ notation.
Also for abbreviations, all letters except the first one should always be lowercased.
==========================

[CAUTION]
.Open issue: location of common JSON schemas
====
Under discussion: guidelines how to publish JSON schemas that are used in multiple APIs. See issue #7.
====

CAUTION: Open issue #14: representing JSON Merge Patch in JSON schema

[caption="Rule {counter:rule-number}: "]
.additionalProperties
====
`additionalProperties` can be used to put restrictions on other properties of a JSON object than those specified in the schema.

Schemas SHOULD avoid using `additionalProperties` declarations, in order to support schema evolution.

An exception is its use to describe an object representing a map of key-value pairs, rather than a business object.
====

An example of `additionalProperties` is the declaration of the types of resources in an `embedded` object, as described in <<Embedded resources>>.

[caption="Rule {counter:rule-number}: "]
.readOnly properties
====
Properties SHOULD  be declared readOnly when appropriate.

Properties can be declared `readOnly: true`.
This means that it MAY be sent as part of a response but MUST NOT be sent as part of the request.
Properties marked as readOnly being true SHOULD NOT be in the required list of the defined schema.

Examples are properties that are computed from other properties, or that represent a volatile state of a resource.
====

**Useful references**

[options="header"]
|===
|Name|Link
|JSON Schema Official Site|http://json-schema.org[http://json-schema.org^]
|JSON Schema Core specification|http://json-schema.org/latest/json-schema-core.html[http://json-schema.org/latest/json-schema-core^]
|JSON Schema Validation specification|http://json-schema.org/latest/json-schema-validation.html[http://json-schema.org/latest/json-schema-validation^]
|JSON Schema User guide|http://spacetelescope.github.io/understanding-json-schema[http://spacetelescope.github.io/understanding-json-schema^]
|XMLSpy 2017|The XML editor now fully supports JSON and JSON schemas
|JSON Schema generator based on sample JSON message|http://jsonschema.net​
|Mock JSON message generator | http://schematic-ipsum.herokuapp.com
|===

'''
