== Changelog
* 2019-01-22
** modified <<API specifications>> guidelines for reusable definitions to be put in Swagger files instead of multiple smaller JSON schema files
** gCloud JSON Schemas refactored to this new file structure
** updated list of Swagger editors and code generators in <<Tools>>
** added guidelines about <<Tracing>> with standardized HTTP headers
** add OpenAPI example of multi-valued query param to <<resources>>
** added rule: place reference data resources in `/refData` (<<doc-resource>>)
** add list of reserved resource names to <<Reserved words>>
** document `select` reserved query param to filter resource representation (<<document-consult>>)
* 2018-11-26
** add SelfLink type in <<Hypermedia controls>>
** recommend American English for <<JSON>> property names and <<JSON data types>>
** add recommendations on typing of properties in <<JSON data types>> (integer/string, enums)
* 2018-09-09
** HttpLink type updated in <<Hypermedia controls>> to be read only instead of required
** new rule in <<JSON data types>> for enum values
* 2018-08-09
** Standardized Problem response for several use cases in <<Error handling>> and updated Problem examples throughout the guide
* 2018-08-08
** added clarifications and example for use of `HttpLink` to <<Hypermedia controls>>
** changed guideline for JSON Schemas to single root type per file and add rule on common BelGov schemas
* 2018-06-29
** added files with common data types containing types referenced throughout the guide
** added MergePatch type to <<Partial update>>
** added guidelines for <<Long running tasks>>
* 2018-05-28
** added <<Caching>> guidelines
* 2018-04-25
** added <<Internationalization (I18N)>> guidelines
** updated <<Non-CRUD operations>>, allowing verb as child resource and GET method in some cases
** update format of version number in <<API specifications>>
** added contact email address in <<Introduction>>
** prefix `BelGov-` added for custom <<reserved HTTP headers>>
* 2018-04-19
** guidelines about reusable JSON Schemas
* 2018-04-18
** added <<versioning>> guidelines
** removed collector, added <<Non-CRUD operations>> under <<document>> section
* 2018-03-14
** added reserved HTTP headers and rule on custom http headers (<<reserved-HTTP-headers>>)
** content negotiation and JSON subtypes added to <<Media Types>>
** <<collections-consult>>: empty items array mandatory when collection is empty
** relax the rule on `additionalProperties` to be compatible with its use for embedded resources
* 2018-03-07
** <<Error handling>>: use of RFC 7807
