== Controller

A controller resource models a _procedural concept_. Controller resources are like executable functions, with parameters and return values; inputs and outputs.

WARNING: Never use controllers for CRUD operations.

A REST API can rely on controller resources to perform application-specific actions that cannot be logically mapped to one of the standard methods (create, retrieve, update, and delete).

[caption="Rule {counter:rule-number}: "]
.Controllers
==========================
Controller names typically appear as the last segment in a URI path, with no child resources to follow them in the hierarchy. 

This is the *only resource type where a verb can be used to indicate the action to execute*.

Always invoke controllers using HTTP <<post>>.
==========================
The example below shows a controller resource that allows a client to resend an alert to a user:

```
POST /alerts/245743/resend
```

NOTE: Controller resources are not considered RESTful. They represent a remainder of RPC, XML/HTTP and SOAP. Although controllers can be useful to simplify the API, they shouldn't be overused.

