== Error handling

https://tools.ietf.org/html/rfc7807[Problem Details for HTTP APIs (RFC 7807)^] defines a simple JSON format to convey additional information about an error to an API consumer. This information complements the HTTP status codes [https://tools.ietf.org/html/rfc7231#section-6[RFC7231]].

For any problem occurred during processing, whether it be caused by the client or the server, the API provider supplies

1.  a suitable <<Status codes,status code>>: 4xx for consumer or 5xx for server errors
2.  a RFC 7807 problem detail message


.Problem Details JSON schema (from link:schemas/problem/v1/problem-v1.yaml[problem-v1.yaml])
```yaml
Problem:
  description: A Problem Details object (RFC 7807)
  type: object
  properties:
    type:
      type: string
      format: uri
      description: An URI reference that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g. using HTML).
      default: about:blank
    title:
      type: string
      description: A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized)
      example: Service Unavailable
    status:
      type: integer
      format: int32
      description: The HTTP status code generated by the origin server for this occurrence of the problem.
      minimum: 400
      maximum: 600
      exclusiveMaximum: true
      example: 503
    detail:
      type: string
      description: A human-readable explanation specific to this occurrence of the problem
    instance:
      type: string
      format: uri
      description: A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
```

[.rule, caption="Rule {counter:rule-number}: "]
.Media type
==========================
RFC 7807 defines the media type `application/problem+json`
==========================


[.rule, caption="Rule {counter:rule-number}: "]
.Unique error id
==========================
Each status message contains a unique id to track the message and store it for support use later on.
==========================

```
HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Type: application/problem+json
X-Correlation-Id: d9e35127-e9b1-4201-a211-2b52e52508df
```
```json
{
  "type": "https://www.gcloud.belgium.be/rest/problems/resourceNotFound"
  "instance": "d9e35127-e9b1-4201-a211-2b52e52508df",
  "status": 404,
  "title": "Enterprise not found",
  "detail": "No enterprise with CBE number 0206731645",
  "invalidParams": [
      {
        "in": "path",
        "name": "enterpriseNumber",
        "reason": "the enterprise number is not assigned",
        "value": "0206731645"
      }
  ]
}
```

[.rule, caption="Rule {counter:rule-number}: "]
.Consumer-friendly details
==========================
Each status message contains a ```detail``` property to provide specific information about the failing requests to the consumer.
==========================

```
POST /enterprises/0203456798/employers
{
    "name": "John"
}
```

```
HTTP/1.1 409 Conflict
Content-Type: application/problem+json
{
   "instance": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "type": "/problems/enterpriseInactive",
   "title": "Conflict",
   "status": 409,
   "detail": "Enterprise 0203456798 has ceased its activities since 2017-01-01"
}
```

[.rule, caption="Rule {counter:rule-number}: "]
.Error sanitization
==========================
A problem cannot leak sensitive implementation and infrastructure details. Providers must strip this information (e.g. DB error codes, internal hostnames, stacktraces) before returning the problem detail to the consumer.
==========================

E.g. this should not be returned to a client:
```
HTTP/1.1 500 Internal Server Error
Server: Apache-Coyote/1.1
Content-Type: application/problem+json
```
```json
{
  "instance": "ac19acc6-5e11-4b2a-8c10-f9680998d07a",
  "title": "Internal Server Error",
  "detail": "Unexpected error occurred while processing demand",
  "stackTrace": [  [
      "EJBException: java.lang.RuntimeException: Something horrible happened on the server",
      "org.jboss.as.ejb3.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:191)",
      "org.jboss.as.ejb3.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:282)",
      "org.jboss.as.ejb3.CMTTxInterceptor.required(CMTTxInterceptor.java:345)",
      "org.jboss.as.ejb3.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:243)"
    ],
    [
      "Caused by: java.lang.RuntimeException: Something horrible has happened on the server",
      "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
      "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)",
      "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "java.lang.reflect.Method.invoke(Method.java:606)"
    ]
  ]
}
```

=== Standardized problem types

A list of problem types is standardized for all G-Cloud REST APIs. The problem description has a type defined in `+https://www.gcloud.belgium.be/rest/problems+`.

WARNING: Links to https://www.gcloud.belgium.be/rest/problems are not resolvable at the moment. This will be fixed in the future.


include::problems/badRequest.adoc[leveloffset=3]

.InvalidParamProblem schema definition (from link:schemas/problem/v1/problem-v1.yaml[problem-v1.yaml])
```yaml
InvalidParamProblem:
  description: Problem details for invalid input parameter(s)
  allOf:
    - $ref: '#/definitions/Problem'
    - type: object
      properties:
        invalidParams:
          type: array
          description: An array of parameter OpenAPI violations
          items:
            $ref: '#/definitions/InvalidParam'
InvalidParam:
  type: object
  properties:
    in:
      description: The location of the invalid parameter (cfr Swagger parameters)
      type: string
      enum:
        - body
        - path
        - query
        - header
    name:
      description: The name of the invalid parameter
      type: string
    reason:
      description: A message explaining the violation
      type: string
    value:
      description: The value of the erroneous parameter
      # no type specified, allowing any type. This is valid OpenAPI 2.0 even though some editors may indicate an error (issue #25)
```
include::problems/noAccessToken.adoc[leveloffset=3]
include::problems/invalidAccessToken.adoc[leveloffset=3]
include::problems/expiredAccessToken.adoc[leveloffset=3]
include::problems/missingScope.adoc[leveloffset=3]
include::problems/missingPermission.adoc[leveloffset=3]
include::problems/resourceNotFound.adoc[leveloffset=3]
include::problems/tooManyRequests.adoc[leveloffset=3]


=== API specific problem types

Each API can define its own problem types. The path `/problems/{problemId}` should resolve to a HTML page containing additional information about the specific problem.

```
POST /enterprises/0203456798/employers
{
    "name": "John"
}
```

```
HTTP/1.1 409 Conflict
Content-Type: application/problem+json
{
   "instance": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "type": "/problems/enterpriseInactive",
   "title": "Conflict",
   "status": 409,
   "detail": "Enterprise 0203456798 has ceased its activities since 2017-01-01"
}
```