== Error handling ==

All RESTful services can reuse a default status message to communicate errors in a standardized way to the service consumer.


[CAUTION]
This section needs to be revised.
RFC 7807 will be used instead of the problem message structure described below.

.EHEALTH REMARK
====
ErrorHandling
•	In RFC 7807 there is no error id specified [WISA] --> is een uri
•	Access to statusMessage link, oppassen met externe doc resources (JSON schemas, example REST service, …)
https://git01.smals.be/rest/commons/blob/master/src/main/resources/META-INF/schemas/statusMessage.json
Spec details element: Free format?
====

[caption="Rule {counter:rule-number}: "]
.Unique error id
==========================
Each status message contains a unique id to track the message and store it for support use later on.
==========================

```
HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Type: application/json
```
```json
{
  "id":"d9e35127-e9b1-4201-a211-2b52e52508df", <1>
  "code":"Not Found",
  "message":"No employer with company id 0206731645"
}
```

[caption="Rule {counter:rule-number}: "]
.Consumer-friendly details
==========================
Each status message contains a details property to provide specific information about the failing requests to the consumer.
==========================

```
HTTP/1.1 400 Bad Request
Server: Apache-Coyote/1.1
Content-Type: application/json
```
```json
{
   "id": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "code": "Bad Request",
   "message": "The input message is incorrect",
   "details": [{ <1>
      "kind": "path-param",
      "message": "This value should be numeric",
      "ref": "companyId",
      "value": "abc"
   }]
}
```

[caption="Rule {counter:rule-number}: "]
.Error sanitization
====
Sensitive information like stack traces MUST be stripped before returning messages to the client.
====

E.g. this should not be returned to a client:
```
HTTP/1.1 500 Internal Server Error
Server: Apache-Coyote/1.1
Content-Type: application/json
```
```json
{
  "id": "ac19acc6-5e11-4b2a-8c10-f9680998d07a",
  "code": "Internal Server Error",
  "message": "Unexpected error occured while processing demand",
  "stackTrace": [  [
      "EJBException: java.lang.RuntimeException: Something horrible happened on the server",
      "org.jboss.as.ejb3.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:191)",
      "org.jboss.as.ejb3.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:282)",
      "org.jboss.as.ejb3.CMTTxInterceptor.required(CMTTxInterceptor.java:345)",
      "org.jboss.as.ejb3.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:243)"
    ],
    [
      "Caused by: java.lang.RuntimeException: Something horrible has happened on the server",
      "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
      "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)",
      "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "java.lang.reflect.Method.invoke(Method.java:606)"
    ]
  ]
}
```
