== Error handling ==

All RESTful services can reuse a default status message to communicate errors in a standardized way to the service consumer.


[caption="Rule {counter:rule-number}: "]
.Unique error id
==========================
Each status message contains a unique id to track the message and store it for support use later on.
==========================

```
HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Type: application/json
```
```json
{
  "id":"d9e35127-e9b1-4201-a211-2b52e52508df", <1>
  "code":"Not Found",
  "message":"No employer with company id 0206731645"
}
```

[caption="Rule {counter:rule-number}: "]
.Consumer-friendly details
==========================
Each status message contains a details property to provide specific information about the failing requests to the consumer.
==========================

```
HTTP/1.1 400 Bad Request
Server: Apache-Coyote/1.1
Content-Type: application/json
```
```json
{
   "id": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "code": "Bad Request",
   "message": "The input message is incorrect",
   "details": [{ <1>
      "kind": "path-param",
      "message": "This value should be numeric",
      "ref": "companyId",
      "value": "abc"
   }]
}
```

[caption="Rule {counter:rule-number}: "]
.Error sanitization
==========================
The ESB strips sensible information before returning the status message to client.
==========================

```
HTTP/1.1 500 Internal Server Error
Server: Apache-Coyote/1.1
Content-Type: application/json
```
```json
{
  "id": "ac19acc6-5e11-4b2a-8c10-f9680998d07a",
  "code": "Internal Server Error",
  "message": "Unexpected error occured while processing demand",
  "stackTrace": [  [ <1>
      "EJBException: java.lang.RuntimeException: Something horrible happened on the server",
      "org.jboss.as.ejb3.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:191)",
      "org.jboss.as.ejb3.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:282)",
      "org.jboss.as.ejb3.CMTTxInterceptor.required(CMTTxInterceptor.java:345)",
      "org.jboss.as.ejb3.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:243)"
    ],
    [
      "Caused by: java.lang.RuntimeException: Something horrible has happened on the server",
      "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
      "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)",
      "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "java.lang.reflect.Method.invoke(Method.java:606)"
    ]
  ]
}
```

<1> The backend service can return a complete stacktrace to the ESB. The information is logged, but stripped from the response.

=== SOA error code mapping ===
SOAP messages only use the <<http-500,`500 Internal Server Error`>> code to indicate failure. The SOA guidelines standardized http://integrationsoa/site_nl/standards/errorhandling.html[a set of SOA error codes^] to detail the kind of error. With RESTful services it is unnecessary to redefine these error codes, because we align ourselves to the HTTP standard.

* <<4xx Client Error,4xx status codes>> indicate a problem occurs on client-side
* <<5xx Server Error,5xx status codes>> indicate a problem occurs on server-side 

[cols="1,2,1,2", options="header"]
|====
|SOA code|Description|Origin|HTTP status code mapping
|SOA-00001|Service error|Provider|<<http-500, 500 Internal Server Error>>
|SOA-01001|Service call not authenticated|Consumer|<<http-401, 401 Unauthorized>>
|SOA-01002|Service call not authorized|Consumer|<<http-403, 403 Forbidden>>
|SOA-02001|Service not available. Please contact service desk.|Provider
a|<<http-500, 500 Internal Server Error>> or +
<<http-503, 503 Service Unavailable>>
|SOA-02002|Service temporarily not available. Please try later.|Provider|<<http-503, 503 Service Unavailable>>
|SOA-03001|Malformed message|Consumer|<<http-400, 400 Bad Request>>
|SOA-03002|Message must be SOAP|Consumer|N/A
|SOA-03003|Message must contain SOAP body|Consumer|N/A
|SOA-03004|WS-I compliance failure|Consumer|N/A
|SOA-03005|WSDL compliance failure|Consumer|<<http-405, 405 Method Not Allowed>>
|SOA-03006|XSD compliance failure|Consumer|<<http-400, 400 Bad Request>>
|SOA-03007|Message content validation failure|Consumer
a|<<http-400, 400 Bad Request>> or +
<<http-409, 409 Conflict>>
|====