== Error handling ==

https://tools.ietf.org/html/rfc7807[Problem Details for HTTP APIs (RFC 7807)^] defines a simple JSON format to convey additional information about an error to an API consumer. This information complements the HTTP status codes [https://tools.ietf.org/html/rfc7231#section-6[RFC7231]].

For any problem occurred during processing, whether it be caused by the client or the server, the API provider supplies

1.  a suitable <<Status codes,status code>>: 4xx for consumer or 5xx for server errors
2.  a RFC 7807 problem detail message


.Problem Details JSON schema (from link:schemas/common/v1/Problem.yaml[Problem.yaml])
```yaml
$schema: http://json-schema.org/draft-04/schema#
description: A Problem Details object (RFC 7807)
type: object
properties:
  type:
    type: string
    format: uri
    description: An URI reference that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g. using HTML).
    default: about:blank
  title:
    type: string
    description: A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized)
    example: Service Unavailable
  status:
    type: integer
    format: int32
    description: The HTTP status code generated by the origin server for this occurrence of the problem.
    minimum: 400
    maximum: 600
    exclusiveMaximum: true
    example: 503
  detail:
    type: string
    description: A human-readable explanation specific to this occurrence of the problem
  instance:
    type: string
    format: uri
    description: A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
```

[.rule, caption="Rule {counter:rule-number}: "]
.Media type
==========================
RFC 7807 defines the media type `application/problem+json`
==========================


[.rule, caption="Rule {counter:rule-number}: "]
.Unique error id
==========================
Each status message contains a unique id to track the message and store it for support use later on.
==========================

```
HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Type: application/problem+json
X-Correlation-Id: d9e35127-e9b1-4201-a211-2b52e52508df
```
```json
{
  "instance":"d9e35127-e9b1-4201-a211-2b52e52508df",
  "title":"Not Found",
  "status": 404,
  "detail":"No employer with company id 0206731645"
}
```

[.rule, caption="Rule {counter:rule-number}: "]
.Consumer-friendly details
==========================
Each status message contains a details property to provide specific information about the failing requests to the consumer.
==========================

#TODO# clarify list of standardized problem types (APIs can overrdie this locally with additional information)


[.rule, caption="Rule {counter:rule-number}: "]
.Error sanitization
==========================
A problem cannot leak sensitive implementation and infrastructure details. Providers must strip this information (e.g. DB error codes, internal hostnames, stacktraces) before returning the problem detail to the consumer.
==========================

E.g. this should not be returned to a client:
```
HTTP/1.1 500 Internal Server Error
Server: Apache-Coyote/1.1
Content-Type: application/problem+json
```
```json
{
  "instance": "ac19acc6-5e11-4b2a-8c10-f9680998d07a",
  "title": "Internal Server Error",
  "detail": "Unexpected error occurred while processing demand",
  "stackTrace": [  [
      "EJBException: java.lang.RuntimeException: Something horrible happened on the server",
      "org.jboss.as.ejb3.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:191)",
      "org.jboss.as.ejb3.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:282)",
      "org.jboss.as.ejb3.CMTTxInterceptor.required(CMTTxInterceptor.java:345)",
      "org.jboss.as.ejb3.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:243)"
    ],
    [
      "Caused by: java.lang.RuntimeException: Something horrible has happened on the server",
      "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
      "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)",
      "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "java.lang.reflect.Method.invoke(Method.java:606)"
    ]
  ]
}
```

=== Schema validation error

Whenever a client submits a request not compliant to the Swagger definition of the API, the service returns a `400 Bad Request`.

```
POST /companies/abc

{
    "mandator": {
        "cbeNbr": "123456"
    }
}
```

```
HTTP/1.1 400 Bad Request
Content-Type: application/problem+json

{
   "instance": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "title": "Bad Request",
   "status": 400,
   "detail": "The input message is incorrect",
   "invalidParams": [
       {
          "in": "path",
          "name": "cbeNbr",
          "reason": "should be numeric",
          "value": "abc"
       },
       {
          "in": "body",
          "name": "mandator.cbeNbr",
          "reason": "have minimum 9 digits",
          "value": "123456"
       }
   ]
}
```

|===
|Field |Description

|invalidParams
|An array of schema violations

|invalidParams[].in
|The location of the error, e.g. body, path, query, header (cfr Swagger parameters)

|invalidParams[].name
|The name of the invalid parameter

|invalidParams[].reason
|A message explaining the violation

|invalidParams[].value
|The value of the erroneous parameter
|===

=== Authentication

```
GET /companies/202239951
```

```
HTTP/1.1 401 Unauthorized
Content-Type: application/problem+json

{
   "instance": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "type": "https://www.gcloud.belgium.be/rest/problems/noAccessToken",
   "title": "Unauthorized",
   "status": 401,
   "detail": "Missing access token"
}
```

|===
|Type|Description

|/problems/noAccessToken
|The `Authorization` HTTP header doesn't contain a access token.

|/problems/invalidAccessToken
|The `Authorization` HTTP header contains an invalid access token (e.g. should be JWT, unrecognized authorization server).

|/problems/expiredAccessToken
|The access token is expired and cannot be used anymore.

|/problems/revokedAccessToken
|The access token has been revoked.

|===

=== Authorization

Either the client doesn't have the right scope to invoke the operation.

```
GET /companies/202239951
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```

```
HTTP/1.1 403 Forbidden
Content-Type: application/problem+json

{
   "instance": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "type": "/problems/missingScope",
   "title": "Forbidden",
   "status": 403,
   "detail": "not permitted to consult company resource",
   "requiredScopes": ["company-read"]
}
```

Either the client doesn't have the permission to invoke an operation on a specific resource (data access).

```
PUT /companies/202239951
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```

```
HTTP/1.1 403 Forbidden
Content-Type: application/problem+json

{
   "instance": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "type": "/problems/insufficientPermission",
   "title": "Forbidden",
   "status": 403,
   "detail": "not permitted to update the company details"
}
```

=== Resource not found

In case the resource collection doesn't exist

```
GET /companies/{cbeNbr}

HTTP/1.1 404 Not Found
Content-Type: application/problem+json
```
```json
{
   "instance": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "type": "/problems/resourceNotFound",
   "title": "Not Found",
   "status": 404,
   "detail": "The resource /company doesn't exist"
}
```

In case the resource document doesn't exist

```
GET /companies/{cbeNbr}/invoices/{invoiceId}

HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Type: application/problem+json
```
```json
{
   "instance": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "title": "Not Found",
   "status": 404,
   "detail": "The company doesn't exist",
   "invalidParams": [{
      "in": "path",
      "name": "cbeNbr",
      "reason": "company number does not exist",
      "value": "4074567892"
   }]
}
```

=== Conflicts

```
POST /companies/203456798/employers
{
    "name": "John"
}
```

```
HTTP/1.1 409 Conflict
Content-Type: application/problem+json
{
   "instance": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "type": "/problems/companyInactive",
   "title": "Conflict",
   "status": 409,
   "detail": "Company 203456798 has ceased its activities since 2017-01-01"
}
```


=== Too many requests

```
GET /companies/{cbeNbr}
```
```
HTTP/1.1 429 Too many requests
Content-Type: application/problem+json
{
   "type": "/problems/tooManyRequests",
   "instance": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "title": "Too many requests",
   "status": 429,
   "detail": "No more requests accepted before 2018-08-09T06:56:00Z",
   "limit": "200",
   "retryAfter": "2018-08-09T06:56:00Z",
   "retryAfterSec": "60"
}
```