== Error handling

https://tools.ietf.org/html/rfc7807[Problem Details for HTTP APIs (RFC 7807)^] defines a simple JSON format to convey additional information about an error to an API consumer. This information complements the HTTP status codes [https://tools.ietf.org/html/rfc7231#section-6[RFC7231]].

For any problem occurred during processing, whether it be caused by the client or the server, the API provider supplies

1.  a suitable <<Status codes,status code>>: 4xx for consumer or 5xx for server errors
2.  a RFC 7807 problem detail message


.Problem Details JSON schema (from link:https://github.com/belgif/openapi-problem/blob/master/src/main/swagger/problem/v1/problem-v1.yaml[problem-v1.yaml])
```yaml
    Problem:
      description: A Problem Details object (RFC 7807)
      type: object
      properties:
        type:
          type: string
          format: uri
          description: An absolute URI that identifies the problem type
          default: about:blank  # kept for backwards-compatibility, type will be mandatory in problem-v2
        href:
          type: string
          format: uri
          description: An absolute URI that, when dereferenced, provides human-readable documentation for the problem type (e.g. using HTML).
        title:
          type: string
          description: A short, summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
          example: Service Unavailable
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
        instance:
          type: string
          format: uri
          description: An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
```

[.rule, caption="Rule {counter:rule-number}: "]
.Use of RFC 7807 Problem Details
====
Any information on a problem SHOULD be provided in the Problem Detail format, as specified in https://tools.ietf.org/html/rfc7807[Problem Details for HTTP APIs (RFC 7807)^]:

* the media type for problems SHOULD be `application/problem+json`
* `status`: the HTTP status code
* `type`: a unique identifier for the type of the problem that MUST remain stable over time. It can be used by API clients during problem handling.
* `title`: a short summary of the problem type in English
* `instance`: a unique identifier of the problem instance. It could be used to track the message for support purposes.
* `detail`: consumer-friendly information about the specific failing request. It MAY be localized using <<i18n-negotiation, language negotiation>>.
* additional properties may be added to provide more information on the problem

The Problem Details response body MAY be absent when the HTTP status code itself provides sufficient information (e.g. for 405 Method Not Allowed, 406 Not Acceptable or 415 Unsupported Media Type).

This guide applies following additional restrictions on the Problem Details structure:

* `type` and `instance` SHOULD be specified as absolute URIs in order to avoid issues when resolving relative URIs (see <<links>>)
* The `type` property, a stable identifier for the type of problem, is MANDATORY instead of optional
* a new optional `href` property SHOULD be used to provide a URI to human-readable documentation on the problem type instead of dereferencing the `type` value
====

Note that using `href` instead of `type` for documentation intentionally deviates from the recommendation in the RFC.
`href` allows use of a URL for documentation purposes that may change over time, while `type` can be specified as a URN that must remain stable.
This is especially useful for API-specific problem types for which the documentation URL may depend on technical aspects, like deployment environment.


.Example Problem response
====
```
POST /enterprises/0206731645/employers
{
    "name": "John"
}
```

```
HTTP/1.1 404 Not Found
Content-Type: application/problem+json
BelGov-Trace-Id: d9e35127-e9b1-4201-a211-2b52e52508df
```
```json
{
  "type": "urn:problem-type:belgif:resourceNotFound",
  "href": "https://www.gcloud.belgium.be/rest/problems/resourceNotFound.html",
  "instance": "urn:uuid:d9e35127-e9b1-4201-a211-2b52e52508df",
  "status": 404,
  "title": "Resource is not found",
  "detail": "There is no enterprise with CBE number 0206731645",
  "invalidParams": [
      {
        "in": "path",
        "name": "enterpriseNumber",
        "reason": "the enterprise number is not assigned",
        "value": "0206731645"
      }
  ]
}
```
====

[.rule, caption="Rule {counter:rule-number}: ", subs="none"]
.Problem type
====
Problem `type` SHOULD be specified as a URN in one of following formats:

* `urn:problem-type:<org>:<api>:<type>`
* `urn:problem-type:<org>:<type>`

with:

* `<org>`: a short identifier for the organization
* `<api>`: name of the API. It MAY be used for API-specific problem types
* `<type>`: type of the problem in lowerCamelCase

A description of an API-specific problem type MAY be provided as a reference data resource : `/refData/problemTypes/{problemType}`.
If provided, at least the HTML media type SHOULD be supported.
====

Reverse FQDN notation for `<org>` is not recommended in order to keep the identifiers short and readable.

.API-specific problem type
====
```JSON
{
  "type": "urn:problem-type:cbss:socialStatus:searchCriteriaTooWide",
  "href": "https://api.ksz-bcss.fgov.be/socialStatus/v2/refData/problemTypes/urn:problem-type:cbss:socialStatus:searchCriteriaTooWide",
  "status": 400,
  "title": "Search criteria should be more specific",
  "detail": "Only one search parameter specified. Please specify at least two.",
  "instance": "urn:uuid:123e4567-e89b-12d3-a456-426614174000"
}
```
====

[.rule, caption="Rule {counter:rule-number}: "]
.Error sanitization
====
A problem MUST NOT leak sensitive implementation and infrastructure details.
Providers must strip this information (e.g. DB error codes, internal hostnames, stacktraces) before returning the problem detail to the consumer.
====

E.g. this should not be returned to a client:
```
HTTP/1.1 500 Internal Server Error
Server: Apache-Coyote/1.1
Content-Type: application/problem+json
```
```json
{
  "type": "urn:problem-type:belgif:internalServerError",
  "instance": "urn:uuid:ac19acc6-5e11-4b2a-8c10-f9680998d07a",
  "title": "Internal Server Error",
  "detail": "Unexpected error code 24879 in server product XYZ v1.0.1",
  "stackTrace": [  [
      "EJBException: java.lang.RuntimeException: Something horrible happened on the server",
      "org.jboss.as.ejb3.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:191)",
      "org.jboss.as.ejb3.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:282)",
      "org.jboss.as.ejb3.CMTTxInterceptor.required(CMTTxInterceptor.java:345)",
      "org.jboss.as.ejb3.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:243)"
    ],
    [
      "Caused by: java.lang.RuntimeException: Something horrible has happened on the server",
      "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
      "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)",
      "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "java.lang.reflect.Method.invoke(Method.java:606)"
    ]
  ]
}
```

[[standardized-problem-types]]
=== Standardized problem types

A list of problem types is standardized for all G-Cloud REST APIs.
They are defined as URNs of format `+urn:problem-type:belgif:<type>+`.

WARNING: `href` links to descriptions of standardized problem types will change in the future to recommended format containing full problem type identifier without HTML extension.


include::problems/badRequest.adoc[leveloffset=3]

.InvalidParamProblem schema definition (from https://github.com/belgif/openapi-problem/blob/master/src/main/swagger/problem/v1/problem-v1.yaml[problem-v1.yaml])
```yaml
InvalidParamProblem:
  description: Problem details for invalid input parameter(s)
  allOf:
    - $ref: '#/definitions/Problem'
    - type: object
      properties:
        invalidParams:
          type: array
          description: An array of parameter OpenAPI violations
          items:
            $ref: '#/definitions/InvalidParam'
InvalidParam:
  type: object
  properties:
    in:
      description: The location of the invalid parameter (cfr Swagger parameters)
      type: string
      enum:
        - body
        - path
        - query
        - header
    name:
      description: The name of the invalid parameter
      type: string
    reason:
      description: A message explaining the violation
      type: string
    value:
      description: The value of the erroneous parameter
      # no type specified, allowing any type. This is valid OpenAPI 2.0 even though some editors may indicate an error (issue #25)
```
include::problems/noAccessToken.adoc[leveloffset=3]
include::problems/invalidAccessToken.adoc[leveloffset=3]
include::problems/expiredAccessToken.adoc[leveloffset=3]
include::problems/missingScope.adoc[leveloffset=3]
include::problems/missingPermission.adoc[leveloffset=3]
include::problems/resourceNotFound.adoc[leveloffset=3]
include::problems/payloadTooLarge.adoc[leveloffset=3]
include::problems/tooManyRequests.adoc[leveloffset=3]
include::problems/tooManyFailedRequests.adoc[leveloffset=3]
include::problems/internalServerError.adoc[leveloffset=3]
include::problems/badGateway.adoc[leveloffset=3]
include::problems/serviceUnavailable.adoc[leveloffset=3]
