== Error handling ==

https://tools.ietf.org/html/rfc7807[Problem Details for HTTP APIs (RFC 7807)^] defines a simple JSON format to convey additional information about an error to an API consumer. This information complements the HTTP [RFC7230] status codes

For any problem occurred during processing, whether it be caused by the client or the server, the API provider supplies

1.  a suitable <<Status codes,status code>>: 4xx for consumer or 5xx for server errors
2.  a RFC 7807 problem detail message


.Problem JSON schema
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Problem Detail for HTTP APIs (RFC 7807)",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "format": "uri",
      "description": "An URI reference that identifies the problem type.  When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).",
      "default": "about:blank"
    },
    "title": {
      "type": "string",
      "description": "A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable"
    },
    "status": {
      "type": "integer",
      "format": "int32",
      "description": "The HTTP status code generated by the origin server for this occurrence of the problem. ",
      "minimum": 100,
      "maximum": 600,
      "exclusiveMaximum": true,
      "example": 503
    },
    "detail": {
      "type": "string",
      "description": "A human-readable explanation specific to this occurrence of the problem"
    },
    "instance": {
      "type": "string",
      "format": "uri",
      "description": "A URI reference that identifies the specific occurrence of the problem.  It may or may not yield further information if dereferenced."
    }
  }
}
```

[.rule, caption="Rule {counter:rule-number}: "]
.Media type
==========================
RFC 7807 defines the media type `application/problem+json`
==========================


[.rule, caption="Rule {counter:rule-number}: "]
.Unique error id
==========================
Each status message contains a unique id to track the message and store it for support use later on.
==========================

```
HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Type: application/problem+json
X-Correlation-Id: d9e35127-e9b1-4201-a211-2b52e52508df
```
```json
{
  "instance":"d9e35127-e9b1-4201-a211-2b52e52508df",
  "title":"Not Found",
  "status": 404,
  "detail":"No employer with company id 0206731645"
}
```

[.rule, caption="Rule {counter:rule-number}: "]
.Consumer-friendly details
==========================
Each status message contains a details property to provide specific information about the failing requests to the consumer.
==========================

#TODO: standardize the additional fields for most current problems like Bad Request#


```
HTTP/1.1 400 Bad Request
Server: Apache-Coyote/1.1
Content-Type: application/problem+json
```
```json
{
   "instance": "88d8393b-f314-4cb3-8ef8-047971dba4ba",
   "title": "Bad Request",
   "status": 400,
   "detail": "The input message is incorrect",
   "details": [{ <1>
      "kind": "path-param",
      "message": "This value should be numeric",
      "ref": "companyId",
      "value": "abc"
   }]
}
```


[.rule, caption="Rule {counter:rule-number}: "]
.Error sanitization
==========================
A problem cannot leak sensitive implementation and infrastructure details. Providers must strip this information (e.g. DB error codes, internal hostnames, stacktraces) before returning the problem detail to the consumer.
==========================

E.g. this should not be returned to a client:
```
HTTP/1.1 500 Internal Server Error
Server: Apache-Coyote/1.1
Content-Type: application/problem+json
```
```json
{
  "instance": "ac19acc6-5e11-4b2a-8c10-f9680998d07a",
  "title": "Internal Server Error",
  "detail": "Unexpected error occured while processing demand",
  "stackTrace": [  [
      "EJBException: java.lang.RuntimeException: Something horrible happened on the server",
      "org.jboss.as.ejb3.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:191)",
      "org.jboss.as.ejb3.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:282)",
      "org.jboss.as.ejb3.CMTTxInterceptor.required(CMTTxInterceptor.java:345)",
      "org.jboss.as.ejb3.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:243)"
    ],
    [
      "Caused by: java.lang.RuntimeException: Something horrible has happened on the server",
      "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
      "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)",
      "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "java.lang.reflect.Method.invoke(Method.java:606)"
    ]
  ]
}
```
