== Health ==

Each REST API exposes a health resource which simply returns the current status of the service.

When invoked without any access token, the resource simply returns its status. The status code is either ```200 OK``` when the service is up or partialy available, or `503 Service Unavailable` when the service is down or out of service.

.Sample service is up
```json
{
    "status": "UP"
}
```

When invoked with an access token containing a scope ```scope:health```, the resource returns details of its subsystems or components.

.Sample service is down
```json
{
    "status": "DOWN"
}
```

The resource is formalized in the swagger file: https://www.gcloud.belgium.be/rest/swagger/health-swagger.yaml

[cols="1,2,3"]
|===
|​​​​​​​​​<<get>>
|/health
|Check the health status of the API.

3+|Response

|body
a|The status of the service. Details are shown when the client presents a valid access token with ```scope:health```.
a|
[source,json]
----
​​​{
   "status": "UP"
}

{
  "status": "DOWN"
}
----

3+|Response codes
​​|<<http-200,200>>
|OK
|When service is `UP` or `DEGRADED`
​
​​|<<http-503,503>>
|Service Unavailable
|When service is `DOWN`

|===

=== Status levels ===
The health resource returns one of the following status levels indicating the component or system:

[cols="1,1,4", options="header"]
|===
|Status|Status Code|Description
|UP| 200 |is functioning as expected.
|DEGRADED | 200 | is partly unavailable but service can be continued with reduced functionality.
|DOWN| 503 |is suffering unexpected failures
|===
