== Hypermedia controls ==

Thanks to _hypermedia controls_ a client can navigate through the REST API without hardcoding URIs to specific resources. It suffices to know a limited set of entry points and navigate to the desired information. This adds _flexibility_ to the evolution of the API and increases _loose coupling_ between client and server.

=== Links ===

[.rule, caption="Rule {counter:rule-number}: "]
.Links to self and other resources
====
When referencing another resource, a link SHOULD be added using the `href` attribute.
Each resource SHOULD also contain its own location in a `self` attribute at root level of the JSON document.
URIs SHOULD always be absolute.
====

CAUTION: For brevity, most URIs in the style guide examples are shortened, but in reality URIs should always be absolute.

All `href` hyperlinks are derived from this minimal link type:

.HttpLink JSON schema (from link:schemas/common/v1/HttpLink.yaml[HttpLink.yaml])
```YAML
description: A base type of objects representing links to resources.
type: object
properties:
href:
  description: Any absolute URI that is using http or https protocol
  type: string
  format: uri
  readOnly: true
```

`self` hyperlinks are derived from the following type:

.SelfLink JSON schema (from link:schemas/common/v1/SelfLink.yaml[SelfLink.yaml])
```YAML
description: A base type representing a link to the resource's own location within its representation
type: object
properties:
  self:
    description: Absolute URI (http or https) to the the resource's own location.
    type: string
    format: uri
    readOnly: true
```

Links should not be used in request bodies in a PUT, POST or PATCH context, as indicated by the `readOnly: true` property.
In a JSON response, they can be added anywhere.

.Resource links
====
GET {API}/companies/1
```json
{
   "self": "{API}/companies/1[/companies/1^]"
   "owner": {
      "ssin": "12345678901",
      "href": "http://example.org/v1/people/12345678901"
   },
   "website": "https://wwww.mycompany.com"
}
```

PATCH {API}/companies/1
```json
{
   "owner": {
      "ssin": "12345678902"
   },
   "website": "https://wwww.mynewwebsite.com"
}
```

The corresponding JSON Schema includes the link types using `allOf`.
As `website` isn't a reference to another API resource, it is not defined using the `HttpLink` type.
```YAML
definitions:
  Company:
    allOf:
    - "$ref": http://www.gcloud.belgium.be/rest/schemas/common/v1/SelfLink.yaml
    - type: object
      properties:
        owner:
          "$ref": "#definitions/PersonReference"
        website:
          type: string
          format: uri
  PersonReference:
    allOf:
      - "$ref": http://www.gcloud.belgium.be/rest/schemas/common/v1/HttpLink.yaml
      - type: object
        properties:
          ssin:
            "$ref": "#definitions/Ssin"
```



====

Hyperlinks for <<Pagination>> inside collections and self-references should use a simple URI value in combination with their corresponding link relations (next, prev, first, last, self) instead of the extensible link type.

[[collection-links]]
.Pagination links
====
[subs="normal"]
```json
{
   "self": "{API}/companies?page=2&pageSize=10[/companies?page=2&pageSize=10^]",
   "prev": "{API}/companies?page=2&pageSize=1[/companies?page=1&pageSize=10^]",
   "next": "{API}/companies?page=2&pageSize=3[/companies?page=3&pageSize=10^]"
}
```
====

The use of https://tools.ietf.org/html/rfc5988[Web Linking] and http://tools.ietf.org/html/draft-kelly-json-hal[Hypertext Application Language (HAL)] is not recommended.
