== Hypermedia controls ==

Thanks to _hypermedia controls_ a client can navigate through the REST API without hardcoding URIs to specific resources. It suffices to know a limited set of entry points and navigate to the desired information. This adds _flexibility_ to the evolution of the API and increases _loose coupling_ between client and server.

=== Links ===

[.rule, caption="Rule {counter:rule-number}: "]
.Links to self and other resources
====
When referencing another resource, a link SHOULD be added using the `href` attribute.
Each resource SHOULD also contain its own location in a `self` attribute at root level of the JSON document.
URIs SHOULD always be absolute.
====

CAUTION: For brevity, most URIs in the style guide examples are shortened, but in reality URIs should always be absolute.

All `href` hyperlinks are derived from this minimal link type:

.HttpLink JSON schema (from link:schemas/common/v1/HttpLink.yaml[HttpLink.yaml])
```YAML
description: A base type of objects representing links to resources.
type: object
properties:
href:
  description: Any absolute URI that is using http or https protocol
  type: string
  format: uri
required: [href]
```

Links can be added anywhere in a JSON document

[subs="normal"]
```json
{
  "name": "Belgacom",
  "nossRegistrationNumber": "93017373",
  "company": {
    "companyId": "0202239951",
    "href": "{API}/companies/0202239951[/companies/0202239951^]"
  },
  "self": "{API}/employers/93017373[/employers/9301737^]"
}
```


Hyperlinks for <<Pagination>> inside collections and self-references should use a simple URI value in combination with their corresponding link relations (next, prev, first, last, self) instead of the extensible link type.

[[collection-links]]
.Pagination links
====
[subs="normal"]
```json
{
   "self": "{API}/companies?page=2&pageSize=10[/companies?page=2&pageSize=10^]",
   "prev": "{API}/companies?page=2&pageSize=1[/companies?page=1&pageSize=10^]",
   "next": "{API}/companies?page=2&pageSize=3[/companies?page=3&pageSize=10^]"
}
```
====

[[document-links]]
.Document link
====
[subs="normal"]
```json
{
  "name": "CPAS de Silly",
  "nossRegistrationNumber": "3870094",
  "company": {
    "companyId": "0212165526",
    "href": "{API}/companies/0212165526[/companies/0212165526^]"
    }
  },
  "self": "{API}/employers/3870094[/employers/3870094^]"
}
```
====

The use of https://tools.ietf.org/html/rfc5988[Web Linking] and http://tools.ietf.org/html/draft-kelly-json-hal[Hypertext Application Language (HAL)] is not recommended.
