== Internationalization (I18N) ==

Textual descriptions part of a resource may need to be offered in the language of a user.

One of following strategies may be chosen for internationalization:

* Do not offer textual descriptions in the API response. Offer them only separate from the data, for example as a dedicated collection resource in the API returning a code list with descriptions. This list can be cached by a client.
* Only include descriptions in a single language, specified by the caller in the `Accept-Language` header.
* Offer descriptions in all applicable languages, i.e. for APIs offered by the Belgian Government in French, Dutch, German and sometimes English as well. This approach is not scalable to high number of languages.
  The descriptions may be filtered by a `lang` query parameter.

=== Accept-Language

As for <<Media Types>>, HTTP supports content negotiation for the language used in response content.
````
[.rule, caption="Rule {counter:rule-number}: "]
.HTTP language headers
====
Users can inform the server that a specific language is requested by adding the `Accept-Language` HTTP header to each request (http://tools.ietf.org/html/rfc7231#section-5.3.5[RFC 7231]).

Its value is a language tag (https://tools.ietf.org/html/rfc5646[RFC 5646]), consisting of a {iso639-1}[ISO 639-1] lowercase language code, optionally followed by an uppercase country code indicating a country-specific variant.
Internationalized APIs of Belgian Federal Government organizations MUST also support the variants for the official Belgian languages ending on `-BE`.
Multiple languages may be specified in order of preference.
A wildcard `*` matches any language.

The `Content-Language` response header MUST be used to indicate the language used in the response for internationalized content.

In case the server could not honor any of the requested languages, it SHOULD return a <<http-406, 406 Not Acceptable>> error.
If the resource supports caching, the `Vary: Accept-Language` MUST be included in the response.
====

.HTTP language headers
====
.Request headers
```
Accept-Language: nl-BE, nl, fr-BE, fr, en, *
```

.Response headers
```
Content-Language: nl
```
====

=== Multi-language descriptions

It may be decided to include all supported translations for descriptions in a resource's representation.

[.rule, caption="Rule {counter:rule-number}: "]
.Multi-language descriptions
====
A multi-language description SHOULD be represented by a JSON object with {iso639-1}[ISO 639-1] language codes as property names and the corresponding textual description as values.

An API MAY offer to filter the representation to a single language by using the <<query-param-lang,reserved query parameter>> `lang`.
====

A `LocalizedString` type is defined supporting the three official Belgian languages.

.LocalizedString JSON Schema (from link:schemas/common/v1/common-v1.yaml[common-v1.yaml])
```YAML
LocalizedString:
  description: A description specified in multiple languages
  type: object
  properties:
  fr:
    type: string
  nl:
    type: string
  de:
    type: string
```

.Multi-language descriptions
====
.Request
`GET /countries/BE`

.Response
```json
"name": {
 "fr": "Belgique",
 "nl": "België",
 "de": "Belgien"
}
```

.Filtering a single language
`GET /countries/BE?lang=fr`

```json
"name": {
 "fr": "Belgique"
}
```
====