== Internationalisation (I18N) ==

CAUTION: I18N not part of guidelines at the moment. Further open issues in #12

=== Accept-Language

Users can inform the server that a specific language is requested by adding the `Accept-Language` HTTP header to each request (http://tools.ietf.org/html/rfc7231#section-5.3.5[RFC 7231]). Two-letter {iso639-1}[ISO 639-1] codes are used to indicate the requested language.

```
Accept-Language: nl
```

Use: `nl` for Dutch, `fr` for French, `de` for German, `en` for English.

In case the server could not honor the user requested language, it is advisable to ignore the header instead of returning a <<http-406, 406 Not Acceptable>> error code.

=== Localized string

Resources can decide to always return all translations to the client using a `localisedString` object.

.localizedString.json schema
```json
{
 "$schema": "http://json-schema.org/draft-04/schema#",
 "title": "localizedString",
 "type": "object",
 "properties": {
  "fr": {
   "type": "string"
  },
  "nl": {
   "type": "string"
  },
  "de": {
   "type": "string"
  },
 "en": {
   "type": "string"
  }
 }
}
```

.example
```json
"name": {
 "fr": "Belgique",
 "nl": "België",
 "de": "Belgien",
 "en": "Belgium"
}
```

Clients can filter the representation to specify a single language by adding the <<query-param-lang,predefined query parameter>> `lang`.

.example: `GET /countries?lang=fr`
```json
"name": {
 "fr": "Belgique"
}
```
