== Introduction

This style guide for RESTful services is a collaborative effort by several Belgian government institutions.
It aims to improve compatibility between RESTful services offered by government institutions or any other organization adopting the guidelines.

It is a living document, meant to be updated when new interoperability issues arise or when REST-related standards evolve.

The main benefit for choosing RESTful services is to increase flexibility and to offer web service support to client platforms not able to communicate using SOAP web services.

* REST is the defacto standard to communicate with web services from JavaScript and native mobile applications.
* While SOAP is strictly linked to XML and needs complex standards (MTOM, Soap-with-Attachments) to work with other media formats, RESTful services can support this natively.
* WS-* specifications added to SOAP are often overly complex and redundant to the possibilities over the underlying communication protocol (e.g. HTTP).
* REST has become the industry standard for developing APIs on the web (https://developers.google.com/apis-explorer[Google^], https://developers.facebook.com/docs/graph-api/reference[Facebook^], https://developer.amazon.com/public/apis[Amazon^], https://dev.twitter.com/rest/public[Twitter^], etc).

This guide does not include guidelines on how to secure REST APIs.
These are under development by the REST Security Working Group, based on the OpenID Connect and https://tools.ietf.org/html/rfc6749[OAuth 2.0^] standards.
It also doesn't include any specifications on how to represent common business data either (e.g. social security number, address, ...), which are being worked on by the REST Functional Working Group.

Contact: mailto:rest-styleguide@gcloud.belgium.be[rest-styleguide@gcloud.belgium.be]
