== Introduction

This style guide for RESTful services is a collaborative effort by several Belgian government institutions.
It aims to improve compatibility between RESTful services offered by government institutions or any other organization adopting the guidelines.

This guide is a living document, updated when new interoperability issues arise or when REST-related standards evolve.
All changes are reviewed by the REST design workgroup, in which the Belgian government organizations are represented.
If you find errors or omissions, or want to contribute, you can open an issue or pull request on https://github.com/belgif/rest-guide[GitHub].

The main benefit for choosing RESTful services is to increase flexibility and to offer web service support to client platforms not able to communicate using SOAP web services.

* REST is the defacto standard to communicate with web services from JavaScript and native mobile applications.
* While SOAP is strictly linked to XML and needs complex standards (MTOM, Soap-with-Attachments) to work with other media formats, RESTful services can support this natively.
* WS-* specifications added to SOAP are often overly complex and redundant to the possibilities over the underlying communication protocol (e.g. HTTP).
* REST has become the industry standard for developing APIs on the web (https://developers.google.com/apis-explorer[Google^], https://developers.facebook.com/docs/graph-api/reference[Facebook^], https://developer.amazon.com/public/apis[Amazon^], https://dev.twitter.com/rest/public[Twitter^], etc).

Topics not covered in this guide:

* Securing REST APIs. Guidelines are under development by the REST Security Working Group, based on the OpenID Connect and https://tools.ietf.org/html/rfc6749[OAuth 2.0^] standards.
* Semantics of common business data (e.g. social security number, address, ...). These are managed by the REST Functional Working Group in the https://github.com/belgif/fedvoc[belgif fedvoc repository].
* OpenAPI specifications for common data types can be found https://github.com/belgif/rest-guide/tree/master/src/main/asciidoc/schemas[here].

.Links
****
* Sources: https://github.com/belgif/rest-guide
* Issues: https://github.com/belgif/rest-guide/issues
* Contact: mailto:rest-styleguide@gcloud.belgium.be[rest-styleguide@gcloud.belgium.be]
****

[NOTE]
====
For brevity most URIs in examples are shortened, but in practice URIs should be in absolute notation.
====

*License*
```
This work is licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
```