== JSON

All RESTful services must support *JSON* (Javascript Object Notation https://tools.ietf.org/html/rfc7159[RFC 7159^]).


=== JSON object

For extensibility, the payload of a RESTful request or response should always be a JSON object (instead of an array, string , number, etc). This way the request or response can always be extended with new properties.

Service consumers should be aware that JSON objects can always be extended with additional JSON properties. This shouldn't break the client code. The unknown properties must be _ignored_.

=== JSON properties


[.rule, caption="Rule {counter:rule-number}: "]
.All JSON property names SHOULD be in English and written in _lowerCamelCase_ notation.
==========================
All JSON property names are in English and are written in _lowerCamelCase_ notation.
Also for abbreviations, all letters except the first one should always be lowercased.
Do not use underscore or hyphens for composite words.

Properties from other standards, like OpenID Connect and OAuth2 are an exception to this rule.
==========================

CAUTION: open issue: British or American English? (CBSS remark)

[subs="normal"]
```json
{
  "name": "Belgacom",
  "nssoNbr": 93017373,
  "company": {
    "cbeNbr": 202239951
  }
}
```

[.rule, caption="Rule {counter:rule-number}: "]
.Null values
==========================
Properties with a `null` value SHOULD be stripped from the JSON message.

A notable exception to this rule are JSON Merge Patch requests, in which a `null` value indicates the removal of a JSON property.

Note that this rule doesn't apply to empty values (e.g. empty strings `""` or empty arrays `[]`) as they are considered different from a `null` value.
==========================

|===
|*NOK*|*OK*
a|[subs="normal"]
```json
{
  "name": "Belgacom",
  "nssoNbr": 93017373,
  "enterprise": null
}
```

a|[subs="normal"]
```json
{
  "name": "Belgacom",
  "nssoNbr": 93017373
}
```
|===

**The JSON properties have no specific order inside a JSON object.**

[cols="1,1"]
|===
a|[subs="normal"]
```json
{
  "name": "Belgacom",
  "nssoNbr": 93017373
}
```


a|[subs="normal"]
```json
{
  "nssoNbr": 93017373,
  "name": "Belgacom"
}
```
|===

**Dates are written in ISO 8601 full-date format: yyyy-mm-dd**

See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types[OpenAPI 2.0 data types^] and https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 section 5.6^].

```json
{
  "birthday": "1930-07-19"
}
```

**Date/time are written in ISO 8601 date-time format: yyyy-MM-dd'T'HH:mm:ssXXX**

See http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3.1[JSON Schema Validation 8.3.1. date-time^] and https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 section 5.6^].

.Example UTC
```json
{
  "lastModification": "2016-04-24T09:26:01.5214Z"
}
```

.Example with timezone
```json
{
  "lastModification": "2016-04-24T11:26:00+02:00"
}
```
