== JSON

All RESTful services must support *JSON* (Javascript Object Notation https://tools.ietf.org/html/rfc7159[RFC 7159^]).


=== JSON object

For extensibility, the payload of a RESTful request or response should always be a JSON object (instead of an array, string , number, etc). This way the request or response can always be extended with new properties.

Service consumers should be aware that JSON objects can always be extended with additional JSON properties. This shouldn't break the client code. The unknown properties must be _ignored_.

=== JSON properties

All JSON property names are in English and are written in _pascalCase_ (lower camel case) notation.
Do not use underscore or hypens for composite words.
Properties from other standards, like <<hal-links,HAL standard>>, OpenID Connect and OAuth2 are an exception to this rule.

[subs="normal"]
```json
{
  "name": "Belgacom",
  "nssoNbr": "93017373",
  "enterprise": {
    "enterpriseNbr": "0202239951"
  }
}
```

[caption="Rule {counter:rule-number}: "]
.Null values
==========================
Properties with a `null` value SHOULD be stripped from the JSON message.

A notable exception to this rule are JSON Merge Patch requests, in which a `null` value indicates the removal of a JSON property.

Note that this rule doesn't apply to empty values (e.g. empty strings `""` or empty arrays `[]`) as they are considered different from a `null` value.
==========================

[CAUTION]
.CBSS REMARK
====
-	Representation of filtered/unauthorized properties of a data type
====

|===
|*NOK*|*OK*
a|[subs="normal"]
```json
{
  "name": "Belgacom",
  "nssoNbr": "93017373",
  "enterprise": null
}
```

a|[subs="normal"]
```json
{
  "name": "Belgacom",
  "nssoNbr": "93017373"
}
```
|===

**The JSON properties have no specific order inside a JSON object.**

[cols="1,1"]
|===
a|[subs="normal"]
```json
{
  "name": "Belgacom",
  "nssoNbr": "93017373"
}
```


a|[subs="normal"]
```json
{
  "nssoNbr": "93017373",
  "name": "Belgacom"
}
```
|===

**Dates are written in ISO 8601 full-date format: yyyy-mm-dd**

See http://swagger.io/specification/#data-types-12[Swagger Datatypes^] and https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 section 5.6^].

```json
{
  "birthday": "1930-07-19"
}
```

**Date/time are written in ISO 8601 date-time format: yyyy-MM-dd'T'HH:mm:ssXXX**

See http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3.1[JSON Schema Validation 8.3.1. date-time^] and https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 section 5.6^].

.Example UTC
```json
{
  "lastModification": "2016-04-24T09:26:00Z"
}
```

.Example with timezone
```json
{
  "lastModification": "2016-04-24T11:26:00+02:00"
}
```


[CAUTION]
.VAS REMARK
====
Updatable fields

* For self documentation purpose and to prevent some business logic to be duplicated in the front-end, we decided to return a shadow resource representation where each given property mean the property is updatable. The value of those properties is not important but we decided to use not null values ("x" for text properties, 1 for number properties and true for boolean properties) to allow the client to check if the property is defined or to check if the property is null or not.

* Because updatable properties can differs from one user to another, you should be careful with caching. You can either disable HTTP caching completely (you will find a lot of examples on Google), either use the Vary HTTP header and to specify an header with the user ID.
In the following example, we specify that only the email can be updated.

```json
{ "first_name": "Marcel",
 "last_name" : "Vincent",
 "ssin" : "00000000097",
 "email" : "marcel.vincent@gmail.com",
 "_updatable": {
 "email" : "x"}}
 ```
====
