=== Long running tasks

Some operations need to be performed asynchronously, as they take too long to complete.

[.rule, caption="Rule {counter:rule-number}: "]
.Long running tasks
====
Long running tasks MUST be represented as a resource, created using a POST action.
This POST action returns a `202 Accepted` response with the URL of the task returned in a `Location` HTTP header.
This new resource can be fetched by the client to get the processing status of the task.

When GETting the task resource, the response contains a `status` may be:

* Still processing: status `200 OK` and a representation of the task's current status
* Success: status `303 See Other` with the `Location` header containing the URL of the task's output.
* Failure: status `200 OK` with a representation of the task's status, including the reason of the failure
====

Variations on the above may be required, e.g. if the task has no output, the response on success may be `200 OK` without `Location` header.

.Long running task
====
*Submitting the task*

`POST /images/tasks`

```
HTTP/1.1 202 Accepted
Content-Type: application/json;charset=UTF-8
Location: http://www.example.org/images/tasks/1
Date: Sun, 13 Sep 2009 01:49:27 GMT
```
```JSON
{
  "status": {
    "state": "pending",
    "message": "Your request has been accepted for processing",
    "pingAfter": "2009-09-13T01:59:27Z"
  }
}
```

The response contains a code indicating that the server accepted the request for processing.
`pingAfter` hints when to check for the status at a later time.

*Getting the processing status*

`GET /images/task/1`

_When the server is still processing the task_

```
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
```
```JSON
{
  "status": {
    "state": "pending",
    "message": "Your request is currently being processed.",
    "pingAfter": "2009-09-13T02:09:27Z"
  }
}
```

_When processing has completed_

```
HTTP/1.1 303 See Other
Location: http://www.example.org/images/1
Content-Type: application/json;charset=UTF-8
```
```JSON
{
  "status": {
    "state": "done",
    "message": "Your request has been processed."
  }
}
```

The `Location` header refers to the result of the task.

_In case of failure during processing_

```
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
```
```JSON
{
  "status": {
    "state": "failed",
    "message": "Failed to complete the request.",
    "completed":"2009-09-13T02:10:00Z",
    "problem": {
      "instance": "d9e35127-e9b1-4201-a211-2b52e52508df",
      "title": "Bad Request",
      "status": 400,
      "type": "http://example.org/errors/invalidImageFormat",
      "detail": "Invalid image format"
    }
  }
}
```

Note that the status code is `200 OK` as the retrieval of the task's status succeeded.
The cause of failure is represented using an an embedded Problem object, as defined in <<Error handling>>.
