== Richardson Maturity Model

This model (developed by Leonard Richardson) breaks down the principal elements of a RESTful interface into three steps.
In order to be compliant to the _uniform interface_ as described by Roy Fielding, all three levels must be fulfilled.

. *<<Resources>>* -- Level 1 tackles the question of handling complexity by using divide and conquer, breaking a large service endpoint down into multiple resources, each represented by a unique URI.
. *<<HTTP Methods>>* -- Level 2 introduces a standard set of verbs so that we handle similar situations in the same way, removing unnecessary variation.
. *<<Hypermedia controls>>* -- Level 3 introduces discoverability, providing a way of making a protocol more self-documenting.


[.rule, caption="Rule {counter:rule-number}: "]
.Maturity level
==========================
All REST services *MUST at least respect level 2* and desirably achieve level 3.
==========================

.References
****
* http://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm['Architectural Styles and the Design of Network-based Software Architectures'^] by Roy Fielding. This dissertation defined the REST architectural principles.
* http://martinfowler.com/articles/richardsonMaturityModel.html['Richardson Maturity Model'^] by Martin Fowler
* http://www.crummy.com/writing/speaking/2008-QCon/act3.html['The Maturity Heuristic'^] by Leonard Richardson
****
