== Media Types

The HTTP protocol supports content negotiation for media types of the response.

[.rule, caption="Rule {counter:rule-number}: "]
.Content negotation
====
REST clients SHOULD specify the media type(s) that is(/are) acceptable for the response in the `Accept` HTTP header.

A REST response or request with payload MUST include the `Content-Type` HTTP header to indicate the media type of the HTTP payload.

Status code <<http-406,406>> MUST be used to indicate that the requested media type could not be provided.

Status code <<http-415,415>> MUST be used to indicate an unsupported media type in the request payload.

If a resource supports multiple content types through negotation, the response header `Vary: Accept` MUST be added to avoid undesired cache hits (also see <<Caching>>).
====

.Content negotiation
====
Request HTTP headers:
```
Accept: image/jpeg, image/png
```
Response HTTP headers:
```
Content-Type: image/png
```
====

*JSON*

The primary media type to support is *JSON* (Javascript Object Notation https://tools.ietf.org/html/rfc7159[RFC 7159^]).
The choice for JSON is particularly made for supporting JavaScript clients.

[.rule, caption="Rule {counter:rule-number}: "]
.Representation of structured data
====
Structured data MUST be made available in JSON format.
Always stick to *UTF-8* encoding and specify the charset in the `Content-Type` HTTP header.
====

```
Content-Type: application/json;charset=UTF-8
```

MIME types of format `application/<subtype>+json` may be used for standardized JSON formats, though REST APIs should also accept requests using the generic `application/json` media type:

* `application/merge-patch+json` for JSON Merge Patch payloads (see <<Partial update>>)
* `application/problem+json` for Problem Detail for HTTP APIs (RFC 7807) payloads (see <<Error handling>>)

*XML*

On specific client request, a REST service can expose XML messages defined by *XML Schema*.


```
Content-Type: application/xml;charset=UTF-8
```

Always stick to *UTF-8* encoding and specify the charset in the `Content-Type` HTTP header.

CAUTION: It is not recommended to implement both JSON / XML in each REST service.
It would require to define and implement two representations of the same data.
Automatic conversion between the two standards will almost never give a satisfying result.
