== Media Types

The HTTP protocol supports content negotiation for media types of the response.

[.rule, caption="Rule {counter:rule-number}: "]
.Content negotation
====
REST clients SHOULD specify the media type(s) that is(/are) acceptable for the response in the `Accept` HTTP header.

A REST response or request with payload MUST include the `Content-Type` HTTP header to indicate the media type of the HTTP payload.

Status code <<http-406,406>> MUST be used to indicate that the requested media type could not be provided.

Status code <<http-415,415>> MUST be used to indicate an unsupported media type in the request payload.

If a resource supports multiple content types through negotation, the response header `Vary: Accept` MUST be added to avoid undesired cache hits (also see <<Caching>>).
====

.Content negotiation
====
Request HTTP headers:
```
Accept: image/jpeg, image/png
```
Response HTTP headers:
```
Content-Type: image/png
Vary: Accept
```
====

[discrete]
=== JSON

The primary media type to support is *JSON* (Javascript Object Notation https://tools.ietf.org/html/rfc7159[RFC 7159^]).
The choice for JSON is particularly made for supporting JavaScript clients.

[.rule, caption="Rule {counter:rule-number}: "]
.Representation of structured data
====
Structured data MUST be made available in JSON format.
Always stick to *UTF-8* encoding and specify the charset in the `Content-Type` HTTP header.
====

```
Content-Type: application/json;charset=UTF-8
```

MIME types of format `application/<subtype>+json` may be used for standardized JSON formats, though REST APIs should also accept requests using the generic `application/json` media type:

* `application/merge-patch+json` for JSON Merge Patch payloads (see <<Partial update>>)
* `application/problem+json` for Problem Detail for HTTP APIs (RFC 7807) payloads (see <<Error handling>>)

[discrete]

=== XML

On specific client request, a REST service can expose XML messages defined by *XML Schema*.


```
Content-Type: application/xml;charset=UTF-8
```

Always stick to *UTF-8* encoding and specify the charset in the `Content-Type` HTTP header.

CAUTION: It is not recommended to implement both JSON / XML in each REST service.
It would require to define and implement two representations of the same data.
Automatic conversion between the two standards will almost never give a satisfying result.

[discrete]
[[media-types-openapi]]
=== Media types in OpenAPI

The request and response body's media type are specified in an OpenAPI specification respectively by the `consumes` and `produces` keywords:

* at operation level
* at root level, as default media types for the entire specification

.Specifying media types at operation level
====
```YAML
  /persons/{ssin}/photo:
    get:
      summary: Get the photo of the person
      operationId: getPhoto
      produces:
      - image/jpeg  # for photo
      - application/problem+json # for problems
      parameters:
      - $ref: "person/identifier/v1beta/person-identifier-v1beta.yaml#/parameters/SsinQueryParameter"
      responses:
        "200":
          description: successful operation
          schema:
            type: file
        "400":
          $ref: "#/responses/InvalidSsinResponse"
        "404":
          $ref: "#/responses/UnknownSsinResponse"
```
====

NOTE: OpenAPI 2.0 doesn't support specifying a different media type per status code.

[.rule, caption="Rule {counter:rule-number}: "]
.Default media types
====
OpenAPI 2.0 specifications SHOULD specify following default media types:

```YAML
consumes:
- application/json

produces:
- application/json
- application/problem+json
```
====

