== Monitoring ==

CAUTION: Monitoring not part of guidelines at the moment. Further open issues in #13

Each RESTful service must be actively monitored by sending automatic probes (by default each 10 min). These probes execute a preconfigured monitoring scenario.


=== HealthCheck controller ===

It's mandatory to monitor with a technical resource and not with a business scenario that can easily break. A generic healthCheck resource definition exists, that can easily be integrated into any RESTful service.

[CAUTION]
.EHEALTH REMARK
====
HealtCheck
*	Monitoring returns the XML monitoring message in order to be interpretable by foglight. This is legacy…
*	Should become JSON
====

[NOTE]
.Library soa-monitoring
The http://integrationsoa/rest/dev#monitoring[SOA Monitoring library] facilitates the implementation of the healthCheck resource.

[cols="1,2,3"]
|===
|​​​​​​​​​<<get>>
|/api/healthCheck
|Check the health status of the RESTful service.

3+|​​​Parameters

|`type`|query-param|e.g. ping, default, deep.

3+|Response

|body
a|The controller response reuses the monitoring XML document previously defined for web service and applications.

<1> Status of the service

<2> Description of the service

<3> Deployment information of the service

<4> The list of sanity checks executed
a|
[source,xml]
----
​​​<HealthCheckResponse xmlns="http://services.fgov.be/monitoring/v1">
  <Status> <1>
    <Level>FATAL</Level>
    <Message>Health check failed with 1 error and 0 warnings</Message>
  </Status>
  <Component> <2>
    <Name>REST Reference Service</Name>
    <Version>0.1.0-SNAPSHOT</Version>
    <MavenReference groupId="be.fgov.rest"
                    artifactId="rest-reference-service"/>
    <CatalogPart>REST-REFERENCE-WS</CatalogPart>
  </Component>
  <Location> <3>
    <Environment>TST</Environment>
    <Host>rest-reference-dc-59-ad9os</Host>
    <Port>8080</Port>
    <URL>http://rest-reference.test.paas.socialsecurity.be/REST/demo/v1/api/healthCheck</URL>
  </Location>
  <SanityCheck id="DB-001" description="Executes select from dual" type="DEFAULT"> <4>
    <Status>
      <Level>CRITICAL</Level>
      <Code>DB-001</Code>
      <Message>DataSource not found: java:comp/env/jdbc/PrincipalDB</Message>
    </Status>
    <Resource name="my principal database" type="DB" reference="jdbc/PrincipalDB"/>
    <TimeInMillis>1</TimeInMillis>
  </SanityCheck>
</HealthCheckResponse>
----

3+|Response codes
​​|<<http-200,200>>
|OK
|Default success code
​
|===

==== Modes ====

The healthCheck controller resource executes a serie of sanity checks and returns the health status of the deployed service. The controller can be invoked with three distict modes (via the ```type``` query parameter):

[cols="1,4"]
|===
|PING| The controller returns basic information about the service. This lightweight mode can be used for alive checks / heart beats.
|DEFAULT| The controller executes a serie of sanity checks on its own dependencies (e.g. DB, queues, local EJB). This check is executed every 10 minutes by the active monitoring script in FogLight.
|DEEP| The controller executes a serie of sanity checks on its own dependencies, plus all external dependencies (e.g. web services, remote EJB, etc). This mode gives the most elaborate information about the service and allows to solve integration problems between services. This check is only executed on-demand during troubleshooting or to verify the successful deployment of the service.
|===

==== Status levels ====
The healthCheck controller returns one of the following status levels:

[cols="1,4"]
|===
|OK| All sanity checks succeeded.
|WARNING| At least 1 sanity check reports a possible failure in the near feature (e.g. slowed down response times, queues at 90% capacity, certificate that will expire). The service is still operational.
|CRITICAL| At least 1 sanity check fails, but the service can operate temporary with reduced functionalities (graceful degradation).
|FATAL| At least 1 sanity check fails and causes a fatal problem. The service is unavailable.
|===
