site:
  title: REST Guidelines
  url: https://www.belgif.be/specification/rest
  start_page: api-guide::introduction.adoc
  robots: allow

content:
  sources:
    - url: .
      start_path: guide/src/antora
      branches: HEAD

asciidoc:
  extensions:
    - ./guide/src/antora/extensions/rule-block-extension.js
antora:
  extensions:
    - '@antora/lunr-extension'

ui:
  bundle:
    url: ./ui-bundle.zip
  supplemental_files: ./guide/supplemental-ui

output:
  clean: true
  dir: ./build/site
  destinations:
    - provider: archive
      path: ./build/site.zip
runtime:
  log:
    failure_level: error
