[[api-specs]]
== API specifications

[rule, ctr-first]
.API contract-first approach
====
The contract-first principle SHOULD be followed when developing an API.
In this approach, the specifications of the REST API are created first and not generated from the code.

A code-first approach may sometimes be necessary however, as current state of technology does not always fully support contract-first development.
In this case, special attention should be given that the API specifications remain stable and loosely coupled to the API implementation technology.
====

[[openapi]]
=== OpenAPI

OpenAPI is the dominating standard for REST API documentation, having gained wide industry support.
It is based on http://swagger.io/[Swagger^], which was standardized as OpenAPI.

[rule, oas-contra]
.OpenAPI
====
The description of a new REST API SHOULD be provided using https://spec.openapis.org/oas/v3.0[*OpenAPI 3.0*].
OpenAPI uses the https://spec.openapis.org/oas/v3.0#schema-object[OpenAPI Schema Object] to describe the JSON representation of resources, which is a variant of https://json-schema.org/specification-links.html#draft-5[*JSON Schema*], with some significant incompatibilities.


https://spec.openapis.org/oas/v3.1[OpenAPI 3.1] improves upon OpenAPI 3.0, but to avoid interoperability problems it SHOULD NOT be used yet because it is not sufficiently supported yet by tooling.
====

The OpenAPI standard also includes a list of supported primitive https://spec.openapis.org/oas/v3.0#data-types[data types].

You can visualize OpenAPI documents using some of the tools listed in <<openapi-tools>>.

[rule, ext-docs]
.Additional documentation
====
Any additional documentation SHOULD be linked from the API's OpenAPI definition using the `externalDocs` property.
====

[rule, oas-yaml]
.Use YAML format for OpenAPI
====
OpenAPI documents SHOULD be made available in YAML format, and OPTIONALLY in JSON format as well.

YAML is a superset of JSON which allows a simpler notation, and also allows comments.
According to usage, a conversion step to JSON might be necessary considering limitations of tools.
====

[rule, oas-tags]
.Use tags to group operations
====
When an API has many operations, https://spec.openapis.org/oas/v3.0#tag-object[tags] SHOULD be used to group them together.

An operation SHOULD NOT have more than one tag.

Each tag used on an operation SHOULD also be declared in the top level `tags` list of the OpenAPI document, with an optional description.

The name of a tag SHOULD be stylized like a title, i.e. a word or space-separated word group starting with a capital letter.
====

Using tags will make the visual representation (e.g. SwaggerUI) more readable.
Multiple tags on an operation duplicates the operation in SwaggerUI, which may cause confusion.

Declaring each tag allows linting tooling to detect inconsistencies in tag names.

.Using tags
====
```YAML
tags:
  - name: Employers
    description: Managing employers
  - name: Reference data
paths:
  /employers/{employerId}:
    get:
      summary: Get an employer by its identifier
      tags:
        - Employers
  /employers:
    get:
      summary: Find employers matching given search parameters
      tags:
        - Employers
    post:
      summary: Add a new employer
      tags:
        - Employers
  /refData/employerClasses:
    get:
      summary: Find enterprises matching given search parameters
      tags:
        - referenceData # BAD: doesn't match declared tag name, words aren't separated by space, doesn't start with capital letter
        - Employers # BAD: don't set multiple tags on an operation
```
====

[rule, openapi-opid]
.operationId
====
A unique `operationId` MUST be specified on each operation.
It SHOULD have a lowerCamelCase value following common programming naming conventions for method (function) names.
====

Tools and libraries often use the `operationId` to uniquely identify an operation.
Code generators use it to generate method names and generally take care of transforming it to the language-specific naming conventions (e.g. UpperCamelCase or snake_case).

.operationId
====
```YAML
/health:
  get:
    summary: Check health of the service
    operationId: checkHealth   # Bad values: health, CheckHealth, healthCheck
```
====

[rule, gen-header]
.General HTTP headers
====
[[general-http-headers]]
HTTP header parameters that may be present on all or most operations of an API SHOULD NOT be documented explicitly in the OpenAPI description, as this would clutter the spec and make it difficult to keep up to date. Rather, refer API users to general documentation on these headers.

Operation-specific HTTP header parameters SHOULD be documented.
====

.General vs operation-specific HTTP headers
====
Following are examples of HTTP headers that shouldn't be documented explicitly for each operation:

* `Accept-Language`
* `BelGov-Trace-Id` and `BelGov-Related-Trace-Id` (documented in <<Tracing>>)
* `Authorization`

Examples of headers that should be specified on operations that support them:

* `ETag`
* `If-Modified-Since`
====

[rule, doc-refdata]
.`doc` and `refData` resources
====
[[doc-resource,doc resource]]
The OpenAPI description and other API documentation SHOULD be placed under a special `doc` resource under the API root location.
Access to these documentation resources SHOULD be granted to any user or potential user of the API.

The OpenAPI 3.0 entry document SHOULD be named `openapi.json` or `openapi.yaml`, as specified in the https://spec.openapis.org/oas/v3.0#openapi-description-structure[OpenAPI 3.0 specification].

Resources representing reference data (code lists) specific to an API SHOULD be placed under a `refData` resource.
As reference data is typically static, consider supporting <<Caching>> headers for these resources.
====

Note that these are exceptions to the rule that API resource URLs shouldn't have a file extension.

.`doc` and `refData` resources
====
```
 /doc
     /openapi.json
     /openapi.yaml
     /<optional other documentation>
 /refData
     /<list1OfCodes>
        /<code1>
        /<code2>
        /...
     /<list2OfCodes>
        /...
 /<resource1>
     /...
 /<resource2>
     /...
 ...
```
====

[rule, oas-defaul]
.`default` values
====
[[default-values,default values]]
Absent optional properties in a request are set by the API provider to their `default` value if one is specified in the OpenAPI description.
====

[rule, path-param]
.Naming of path parameters
====
Path parameters SHOULD use *lowerCamelCase* notation.
====

|===
|KO|OK

a|
```YAML
paths:
  /employers/{EmployerId}:
    # ....
```

a|
```YAML
paths:
  /employers/{employerId}:
    # ....
```
|===

[rule, oas-exampl]
.Add examples in OpenAPI
====
Add examples to an OpenAPI document.

Examples SHOULD be provided under the `example` or `examples` OpenAPI properties rather than in a description. `examples` allows specifying multiple examples, but can't be used within schema definitions.

Example values MUST be schema-valid.
====

.Examples in OpenAPI
====

[source,yaml,subs="attributes+"]
----
/enterprises/{enterpriseNumber}:
  get:
    operationId: getEnterprise
    parameters:
    - in: path
      name: enterpriseNumber
      required: true
      schema:
        type: string
    responses:
      "200":
        description: successful operation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enterprise'
            examples:
              success:
                description: Successful response with enterprise data
                value: {
                  "name": "Proximus",
                  "enterpriseNumber": "0202239951"
                }
----
====

[rule, oas-comp]
.Component definitions
====
Duplication of definitions (schemas, responses, parameters, etc.) SHOULD be avoided.
Rather, define them once under `components`, from which they can be referenced (using `$ref`).

All component names SHOULD be defined in American English and use _UpperCamelCase_ notation.
For abbreviations as well, all letters except the first one should be lowercased.

Do not use underscores (_), hyphens (-) or dots (.) in a component name, nor use a digit as first letter.
====

[rule, oas-reuse]
.Reusable OpenAPI documents
====
Instead of specifying everything directly in the `openapi.yaml` file of an API, OpenAPI allows to reference schemas (data types) and other components from other files.
These files SHOULD be OpenAPI documents as well that follow the OpenAPI specification and may include schema definitions, but also other component types like parameters, path items, request bodies and responses.

To work around limitations of certain tools, a conversion step to inline the definitions into the `openapi.yaml` entry document may be necessary.

Duplication of definitions in multiple APIs SHOULD be avoided. Rather, put the definition in a reusable OpenAPI document.
OpenAPI documents reusable from multiple APIs SHOULD be organized in this structure:
```
<domain>/<version>/<domain-version>.yaml
<domain>/<subdomain>/<version>/<domain-subdomain-version>.yaml
```

Definitions SHOULD be grouped per (sub)domain in an OpenAPI document.
Each OpenAPI document has its own lifecycle, with a major version number in its directory and file name, that is increased when backwards compatibility is broken.
This version, with optionally a minor and patch version added to it, MUST be specified in the `info` section in the OpenAPI document.
====

While it is not strictly necessary for external definitions to be put in a valid OpenAPI document, doing so makes it possible to use standard OpenAPI tooling on them.

.Reusable OpenAPI document
====
./person/identifier/v1/person-identifier-v1.yaml
```YAML
openapi: "3.0.3"
info:
  title: person-identifier
  description: data types for person identifiers
  version: "1.1.2"
paths: {} # empty paths property required to be a valid OpenAPI document
components:
  schemas:
    Ssin:
      description: "Social Security Identification Number issued by the National Register or CBSS"
      type: string
      pattern: \d{11}
```

A type can be referenced from another OpenAPI document:
```YAML
"$ref": "./person/identifier/v1/person-identifier-v1.yaml#/components/schemas/Ssin"
```
====

[rule, oas-comdef]
.Common definitions for Belgian government institutions
====
[[belgif-openapi-types, Common OpenAPI definitions]]
Common definitions for use by Belgian government institutions are maintained in the https://github.com/belgif?q=openapi&type=&language=[openapi-* GitHub repositories], released as https://github.com/belgif/rest-guide#reusable-openapi-schemas[zip archives, organized per domain] and also available in https://search.maven.org/search?q=g:io.github.belgif.openapi[Maven Central].
Types in these schemas SHOULD be used instead of defining your own variants.

The technical types referenced in this style guide are available in the https://github.com/belgif/openapi-common[openapi-common] and https://github.com/belgif/openapi-problem[openapi-problem] repositories.
Other types for business concepts commonly used by Belgian government institutions are available in other repositories.
====

[[schemas]]
=== Schemas

[rule, oas-types]
.Naming of schemas (data types)
====

As stated in <<rule-oas-comp>>, schema (data type) names should use UpperCamelCase and American English.

In addition, schema names SHOULD NOT include overly generic terms like `info(rmation)` and `data`.

A schema name SHOULD refer to the business meaning rather than how it is defined.
====

|===
|KO|OK

|SSIN | Ssin
|CustomerInformation | Customer
|LanguageEnumeration | Language
|===

[rule, oas-descr]
.Schema description
====
The `description` property MAY provide a textual description of a schema.
The `title` property MUST NOT be used because it hides the actual schema name in visualization tools like Swagger UI.
====

|===
|KO|OK

a|
```YAML
Pet:
  title: a pet in the pet store
  type: object
```

a|
```YAML
Pet:
  description: a pet in the pet store
  type: object
```
|===

`additionalProperties` can be used to put restrictions on other properties of a JSON object than those specified in the schema.

[rule, addi-prop]
.additionalProperties
====
`additionalProperties` SHOULD be used exclusively to describe an object representing a map of key-value pairs.
The keys of such maps don't need to respect the naming rules for JSON properties (lowerCamelCase and English).
====

An example is the description a map of `embedded` resources, as described in <<embedding>>.
Other uses of `additionalProperties` than for maps are to be avoided, in order to support schema evolution.

[rule, prop-req]
.Required properties
====
You can declare properties of a JSON object as mandatory by adding them to the `required` list.

Any properties listed in `required` MUST also be declared in the object's `properties`, either inline or in a referenced subschema.
====

While undeclared `required` properties are permitted by the JSON Schema standard, they are most often the result of an error in the OpenAPI document (typo, oversight when renaming a property, ...). This rule allows linting tools to mark such errors.

.Required properties
====
|===
| *GOOD* | *BAD*

a|
```YAML
type: object
properties:
  givenName:
    type: string
required: [givenName]
```
a|
```YAML
type: object
properties:
  givenName:
    type: string
required: [firstName] # firstName isn't explicitly declared as a property
```
|===
====

[rule, req-valid]
.Unknown input
====
An API SHOULD refuse unknown input, i.e. unknown body (JSON) properties in the payload or unknown query request parameters. A <<Bad Request, Bad Request>> problem response should be returned with an issue of type `urn:problem-type:belgif:input-validation:unknownInput`.

If an operation does allow and process input that is not defined in OpenAPI, its description should explicitly indicate this.

In specific situations, where a (known) input is not needed anymore and can be safely ignored:

* either it can stay in the API definition with  a deprecation flag and a "not used anymore" description
* or it can be removed from the API definition as long as the server ignores this specific input.

Unknown HTTP header parameters MUST be accepted.
====

If unknown request fields would be accepted, certain client errors cannot be recognized by servers, e.g. parameter name typing errors will be ignored and the client's actual intent will not be met.

Unknown HTTP headers are usually metadata added automatically by technical components that do not change the API's expected behavior and thereby can be ignored.

[rule, oas-rdonly]
.readOnly properties
====
Properties SHOULD be declared as `readOnly: true` when appropriate.

This means that the value of the property is managed exclusively by the owning authority,
and attempts by a client to modify the value of this property
are expected to be ignored or rejected.

Examples are an immutable identifier of a document, properties that are computed from other properties, or that represent a volatile state of a resource.

Properties marked as `readOnly` being `true` SHOULD NOT be in the `required` list of the defined schema.
====

Above guideline is compliant with the https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-9.4[definition of `readOnly`] used by the OpenAPI 3.1 Specification.

The OpenAPI 3.0 Specification has a different definition, that allows to omit properties from requests that are both `readOnly` and `required`. This has been changed in OpenAPI 3.1 to achieve full compatibility with the JSON Schema Specification. Hence, to be forward-compatible, OpenAPI documents should not depend on this 3.0 behavior.

[rule, oas-enum]
.Enum values
====
[[enum-rule, Enum values rule]]
A fixed list of possible values of a property can be specified using `enum`.
However, this may make it harder to change the list of possible values, as client applications will often depend on the specified list e.g. by using code generation.

`enum` SHOULD only be used when the list of values is unlikely to change or when changing it has a big impact on clients of the API.

`enum` values SHOULD be valid to the schema in which they are defined.
====

.Enum declaration
====
```YAML
State:
  type: string
  enum:
  - processing
  - failed
  - done
```
====

When defining a type for an identifier or code, like the above example, the guidelines under <<Identifier>> apply, even when not used as a URL path parameter of a document resource.

[rule, dec-type]
.Decimals
====
[[decimals, Decimals]]
Decimal numbers for which the fractional part's precision is important, like monetary amounts, SHOULD be represented by a `string`-based type, with `number` as format. Depending on the context, a regular expression can enforce further restrictions like the number of digits allowed before/after comma or on the presence of a `+`/`-` sign.

When `number` would be used as type instead of `string`, some technologies will convert the values to floating point numbers, leading to a loss of precision and unintended calculation errors.

This problem may also be avoided by using an equivalent integer representation, for example by expressing a monetary amount in Euro cent rather than Euro.
====


Some more background on why floating point numbers can lead to loss of precision, can be found in https://husobee.github.io/money/float/2016/09/23/never-use-floats-for-currency.html[this blog post].

.Number types preserving precision
====
https://github.com/belgif/openapi-money/blob/master/src/main/openapi/money/v1/money-v1.yaml[belgif openapi-money] defines a string-based type for monetary values:
```YAML
MonetaryValue:
  type: string
  format: number # number is a custom string format that is supported by some, but not all tooling
  pattern: '^(\-|\+)?((\d+(\.\d*)?)|(\.\d+))$'  # Variable number of digits, with at least one digit required, before or after the decimal point. Allows both positive and negative values.
  x-examples:
  - "100.234567"
  - "010"
  - "-.05"
  - "+1"
  - "10"
  - "100."
MonetaryAmount:
  description: A monetary amount
  type: object
  properties:
    value:
      "$ref": "#/components/schemas/MonetaryValue"
    currency:
      "$ref": "#/components/schemas/Currency"
  required: [value, currency]
  example:
    value: "0.01"
    currency: "EUR"
```

It also defines integer-based types specific for monetary amounts expressed in Euro cent:
```YAML
EuroCentPositiveAmount:
  description: Money amount in Euro cents >= 0
  type: integer # representation as Euro cent instead of Euro to avoid floating point rounding problems and need for custom 'number' format
  minimum: 0

EuroCentAmount:
  description: 'Money amount in Euro cents, also allows negative amounts.'
  type: integer # representation as Euro cent instead of Euro to avoid floating point rounding problems and need for custom 'number' format
```
====

While the OpenAPI Specification is well suited to document APIs and express constraints on requests and responses, the full expressiveness of OpenAPI schemas may cause interoperability problems with the type system of common programming languages. This guide adds some restrictions on the use of OpenAPI schemas to avoid such problems.

.Composing schemas with allOf
[rule, sch-allof]
====
The `allOf` JSON Schema keyword expresses that a value must be valid against *all* of a list of subschemas.

For `object` types, it can be used to model an inheritance relationship between schemas. For code generation, the first subschema that's a reference (`$ref`) is considered the parent.
Subschemas in an `allOf` SHOULD NOT declare the same properties, because this will lead to problems for code generation tools.

To model polymorphism, the `discriminator` keyword designates a property used to resolve the child schema against which the object will be validated.
It is RECOMMENDED to provide an explicit `mapping` of discriminator values to schemas.
Objects with discriminator values that do not resolve to a child schema, are rejected during validation.
====

[NOTE]
Version 3.0.4 of the OpenAPI Specification added that "a `discriminator` MUST NOT change the validation outcome of the schema". However, most existing tooling currently do reject values that are not valid against their corresponding child schema or cannot be mapped to one.
At time of writing, it is not possible to define schemas that comply with this change in the OpenAPI Specification, while still allowing polymorphism using common tooling.
Therefore, it is currently recommended to consider the discriminator having an effect on validation.

.Using `allOf` to add additional restrictions or metadata
====

|===
|description | example

|
Overriding the description of a property

a|
```YAML
CountryIsoCode:
  description: Country represented by an ISO 3166-1 alpha-2 code
  type: string
  pattern: "^[A-Z]{2}$"
Person:
  type: object
  properties:
    fullName:
      type: string
    citizenship:
      allOf:
      - $ref: "#/components/schemas/CountryIsoCode"
      - description: "Citizenship (nationality) of the person" # overrides description
```

| Adding a pattern restriction on a string
a|
```YAML
MyCode:
  type: string
  minLength: 3
  maxLength: 7
MyRestrictedCode:
  type: string # type string already in MyCode schema, but helps for code generation
  allOf:
  - $ref: "#/components/schemas/MyCode"
  - pattern: "^A.+$" # additional restriction on string value
```

| Making a property of another schema required
a|
```YAML
ObjectSchema:
  type: object
  properties:
    firstProperty:
      type: string
    secondProperty:
      type: string
RestrictedSchema:
  type: object
  required: [firstProperty] # duplicating the `required` constraint here is necessary to make validation work with current swagger-request-validator
  allOf:
  - $ref: "#/components/schemas/ObjectSchema"
  - required: [firstProperty] # makes property defined in ObjectSchema required
    type: object # object type already in ObjectSchema, but will generate inheritance in code generation
```

| *KO* : properties should not be duplicated in subschemas
a|
```YAML
ParentSchema:
  type: object
  properties:
    parentProperty:
      type: string
ChildSchema:
  type: object
  allOf:
  - $ref: "#/components/schemas/ParentSchema"
  - type: object
    properties:
      parentProperty: # redeclaring property from other schema generate duplicate properties in parent and child class when using code generation
        type: string
        pattern: "^A.*$"
```

|===

====

.Using `allOf` for polymorphism
====
```YAML
Parent:
  type: object
  properties:
    parentProperty:
      type: string
    type:
      type: string
  required: [type]
  discriminator:
    propertyName: type
    mapping:
      first: "#/components/schemas/FirstChild"
      second: "#/components/schemas/SecondChild"
FirstChild:
  allOf:
    - $ref: "#/components/schemas/Parent"
    - type: object
      properties:
        firstChildProperty:
          type: string
SecondChild:
  allOf:
    - $ref: "#/components/schemas/Parent"
    - type: object
      properties:
        secondChildProperty:
          type: integer
```

|===
| JSON value | validation result against `Parent` schema

a|```JSON
{
  "type": "first",
  "firstChildProperty": "abc"
}
```
| valid

validated against the `FirstChild` schema

a|```JSON
{
  "type": "second",
  "secondChildProperty": "abc"
}
```
|
invalid

`SecondChild` schema requires secondChildProperty to be integer

a|```JSON
{
  "type": "third",
  "thirdChildProperty": "abc"
}
```
| invalid

No child schema resolved for discriminator value `"third"`
|===
====

.Using `oneOf`
[rule, sch-oneof]
====
The `oneOf` JSON Schema keyword expresses that a value must be valid against *exactly one* of a list of subschemas. A value that is valid for more than one subschema, is considered invalid against the combined `oneOf` schema.

However, many uses of `oneOf` result in incompatibility problems with code generation tooling however. Thereby, use of `oneOf` SHOULD be limited to either:

* subschemas with only a `required` constraint, without a `type` or other constraint
* subschemas with an `enum` of the same simple `type` (i.e. no `array` or `object`)
* subschemas of `type: object`, when a `discriminator` is also defined. Properties may only be defined within the subschemas.
====

Examples below were tested with openapi-generator's https://openapi-generator.tech/docs/generators/java/[Java] and https://openapi-generator.tech/docs/generators/spring/[Spring code generation].

.`oneOf` compatible with tooling
====
These examples generate correct code:
|===
| schema | generated code

a|
```YAML
type: object
description: Exactly one of `propertyA` or `propertyB` properties should be set.
properties:
  propertyA:
    type: string
  propertyB:
    type: string
    oneOf:
    - required: [propertyA]
    - required: [propertyB]
```
| a class with all properties combined, and without required property (non-null) constraints
a|
```YAML
OneOfEnums:
  oneOf:
  - $ref: "#/components/schemas/FirstEnum"
  - $ref: "#/components/schemas/SecondEnum"
FirstEnum:
  type: string
  enum:
  - A
  - B
SecondEnum:
  type: string
  enum:
  - C
  - D
```
| an enum class `OneOfEnums` that enumerates all values of `FirstEnum` and `SecondEnum`
a|
```YAML
PolymorphicValue:
# no properties may be defined in this schema
  oneOf:
    - $ref: "#/components/schemas/ChildA"
    - $ref: "#/components/schemas/ChildB"
  discriminator:
    mapping:
      "a": ChildA
      "b": ChildB
    propertyName: type
BaseSchema:
  # a common base for the Child schemas is optional
  type: object
  description: Common parent for an entity
  required:
    - type
    - sharedProperty
  properties:
    type: # the discriminator property must be defined and required in the oneOf subschemas
      type: string
    sharedProperty:
      type: string
ChildA:
  allOf:
    - $ref: '#/components/schemas/BaseSchema'
    - type: object
      description: childA type
      required:
        - propertyA  # makes the schema mutually exclusive with ChildB
      properties:
        propertyA:
          type: string
ChildB:
  allOf:
    - $ref: '#/components/schemas/BaseSchema'
    - type: object
      description: childB type
      required:
        - propertyB # makes the schema mutually exclusive with ChildA
      properties:
        propertyB:
          type: string
```
|
A `PolymorphicValue` interface with only the `type` property and `@JsonSubType` annotations.

`ChildA` and `ChildB` classes implementing `PolymorphicValue` and extending a class `BaseSchema`.

This requires setting `useOneOfInterfaces` to `true` in openapi-generator.
|===
====

Following example illustrates **bad usage** of `oneOf`, as its subschemas are not designed to be mutually exclusive:

```YAML
Agent:
  type: object
  oneOf:
  - $ref: "#/components/schemas/Citizen"
  - $ref: "#/components/schemas/Professional"
Citizen:
  type: object
  properties:
    ssin:
      $ref: "./belgif/person/identifier/v1/person-identifier-v1.yaml#/components/schemas/Ssin"
  required: [ssin]
Professional:
  type: object
  properties:
    ssin:
      $ref: "./belgif/person/identifier/v1/person-identifier-v1.yaml#/components/schemas/Ssin"
    enterpriseNumber:
      $ref: "./belgif/organization/identifier/v1/organization-identifier-v1.yaml#/components/schemas/EnterpriseNumber"
  required: [ssin, enterpriseNumber]
```

Any valid `Professional` object is now invalid against the `Agent` schema, e.g.:
```JSON
{
  "ssin": "53480200724",
  "enterpriseNumber": "0123456789"
}
```

Schemas allow unspecified additional properties by default, so this value is valid against `Citizen` regardless of the `enterpriseNumber` property.
Being valid for both subschemas, means that it is invalid against the combined `oneOf` schema. Alternatively, polymorphism with `allOf` and `discriminator` can be used, or a single `Agent` schema which specifies all properties directly.
Disallowing additional properties isn't recommended, as it limits API evolvability.

These examples *do not work* as expected:

|===
| problematic schema  | generated code

a|
```YAML
oneOf:
- type: string
- type: integer
```
| empty class

a|
```YAML
OneOfTypesSchema:
  oneOf:
  - $ref: "#/components/schemas/StringSchema"
  - $ref: "#/components/schemas/AlsoStringSchema"
StringSchema:
  type: string
AlsoStringSchema:
  type: string

| empty class

a|
```YAML
OneOfTwoObjects:
  oneOf:
    - $ref: "#/components/schemas/ChoiceA"
    - $ref: "#/components/schemas/ChoiceB"
ChoiceA:
  type: object
  properties:
    propertyA:
      type: string
    sharedProperty:
      type: string
      pattern: "^A.*$"
  required: [propertyA]
ChoiceB:
  type: object
  properties:
    propertyB:
      type: string
    sharedProperty:
      type: string
      pattern: "^B.*$"
  required: [propertyB]
```
a|
With option `useOneOfInterfaces` set to `false`, a class `OneOfTwoObjects` with:

* both `propertyA` and `propertyB` listed as required (non-null annotation)
* only the pattern constrained of `ChoiceB` applied to `sharedProperty`

With `useOneOfInterfaces` set to `true`, an empty interface `OneOfTwoObjects` that doesn't allow deserialization because of missing `@JsonSubType` annotation (no discriminator).

|===

[[openapi-tools]]
=== Tools

Following tools can be used to edit OpenAPI documents

[options="header"]
|===
|Name|Link| Description
|Swagger UI | https://swagger.io/swagger-ui/ | Browser application. Graphical and text view of OpenAPI documents. Does not support references to external files.
|Zalando's Swagger plugin | https://github.com/zalando/intellij-swagger | Open Source plugin for IntelliJ. Text-only editor.
|Stoplight Studio | https://github.com/stoplightio/studio/releases | Commercial editor with a free version. Graphical and text view, both web based or as desktop application. Supports validation of API style guides (https://stoplight.io/open-source/spectral[Spectral]).
|42Crunch OpenAPI (Swagger) Editor for VS Code|https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi|Open Source plugin for Visual Studio Code. Text editor with SwaggerUI preview and multi-file support.
|42Crunch OpenAPI (Swagger) Editor for IntelliJ|https://plugins.jetbrains.com/plugin/14837-openapi-swagger-editor|Plugin for IntelliJ. Text editor with multi-file support.
|IntelliJ OpenAPI Specifications |https://www.jetbrains.com/help/idea/openapi.html|Plugin bundled with IntelliJ Ultimate (commercial). Text editor with SwaggerUI preview and multi-file support.
|===

Following tools can be used to generate server stubs and API client libraries from OpenAPI documents.

[options="header"]
|===
|Name|Link| Comments
|openapi-generator| https://openapi-generator.tech/ | Started as fork of swagger-codegen.
|swagger-codegen| https://github.com/swagger-api/swagger-codegen|
|===

Following tools allow to verify REST styleguide rules for an OpenAPI document:

|===
|Name | Link | Comments

|belgif-rest-guide-validator | https://github.com/belgif/rest-guide-validator | Open Source Maven Plugin to validate OpenAPI document against rules in this guide

|Spectral a| https://stoplight.io/open-source/spectral | Open Source tool (javascript-based) to enforce REST styleguide rules.

_Note:_ There currently is no implementation of this REST guide for Spectral.

|===
=== References

[options="header"]
|===
|Name|Link
|OpenAPI 3.0 specification| http://spec.openapis.org/oas/v3.0.3.html
|Swagger's OpenAPI Guide | https://swagger.io/docs/specification/v3_0/about/
|===
