== Changelog
* 2025-xx-yy
** Recommend OpenAPI 3.0 and remove OpenAPI 2.0-specifics throughout the guide

* 2024-12-02
** add a list of <<related-belgif>>
** new rule <<rule-prop-req>> on declaring properties as `required`
** new rule <<rule-openapi-opid>>: recommend the use of `operationId`
** update rule <<rule-jsn-null>>: clarify use of `null`
** new rule <<rule-doc-patch>> on JSON Merge Patch, illustrating the use of nullable properties
** update rule <<rule-err-problem>>: provide structured data in additional properties and recommend against parsing `title` or `description`
** clarify that time offsets are mandatory for `date-time` values in <<json-date-time,JSON>>
** update rule: <<rule-oas-exampl>> recommending to add examples, and clarify specifics of OpenAPI 2.0 and 3.0

* 2024-04-05
** update <<rule-oas-tags>>: add new guidelines on tags (declared, style, no more than one tag on an operation)
** new: rule <<rule-oas-comp>> applies naming guidelines on all types of components (previously in <<rule-oas-types>> only for schemas)
** added motivation for <<rule-oas-rdonly>> why required properties shouldn't be readOnly
** clarify that health status should be from client point-of-view in <<health>>

* 2024-01-31
** new: a document may also be a singleton that's not part of a collection (<<document-singleton>>)
** new: path parameter names should use lowerCamelCase <<rule-path-param>>
** update: clarify that query parameters should use lowerCamelCase <<rule-uri-notat>>
** update: the name of a multi-value query parameter should be singular if it's a noun <<rule-qry-multi>>
** new: explicit rule and clearer guidelines on `GET /health` resource <<rule-hlth-res>>

* 2023-10-05
** update: <<rule-req-valid>> issue type for unknown input is renamed
** new: rule <<rule-hdr-case>> on case-insensitivity of HTTP headers
** update: explicit rules for guidelines: <<rule-meth-http>> and <<rule-stat-codes>> (use of appropriate HTTP methods and status codes), <<rule-col-sort>> (sorting a collection)
** update: improved overview table for the use of HTTP methods <<rule-meth-http>>
** update: corrected use of status 303: allowed on all methods in overview table <<rule-stat-codes>>
** update: links to the releases of common OpenAPI definitions are added to <<rule-oas-comdef>>
** update: Problem Details for HTTP APIs is updated to RFC 9457 which obsoletes RFC 7807 throughout the guide
* 2023-06-14
** add /doc/openapi.[json,yaml] to list of reserved resources <<Resource names>>
** updated <<rule-id-name>>: naming convention for OpenAPI types for identifiers and codes
** updated <<rule-hyp-links>>: avoid cross-API links, make self links optional
** new: <<rule-req-valid>>: handling unknown request parameters
** updated list of <<openapi-tools,OpenAPI tools>>
* 2023-03-17
** Rule identifier with anchor added for each rule in the guide
** Updated <<rule-jsn-naming>>: naming of JSON properties
** Updated <<rule-id-name>> with new naming conventions for identifiers and codes

.Older changes
[%collapsible]
====
* 2022-12-07
** new: Representing <<default-problem-response, general problem types in OpenAPI>>
** new: Representing <<general-http-headers,general and operation-specific HTTP headers in OpenAPI>>
* 2022-10-27
** updated: the response body when creating a resource may also contain partial or full resource (<<create-resource, Create a new resource>>)
* 2022-05-20
** move REST guide to belgif.be, updating href problem links
* 2022-03-31
** new: use string based types for decimals when precision is important (<<decimals>>)
** updated: new type <<input-validation-schema,InputValidationProblem>> for problems of type `badRequest` and `resourceNotFound` (breaking change)
** updated: clarify the use of multiple query parameters to filter a collection (<<filtering>>)
* 2022-02-02
** new: designing new <<Identifier,identifiers and codes>> or using existing numerical ones
** updates for OpenAPI 3.0 support throughout the entire guide
** new: <<Service Unavailable>> problem type (http 503)
** added: use Retry-After HTTP header in <<Too Many Failed Requests>> and <<Too Many Requests>>
* 2021-06-24
** updated: use URNs as problem type and add href for problem documentation (<<Error handling>>)
** updated: clarify use of charset in JSON media type (<<media-types>>)
** added: how to specify media types in OpenAPI 3 (<<media-type-openapi3>>)
* 2020-12-02
** new: standardized problem types internalServerError, badGateway, tooManyFailedRequests, payloadTooLarge (<<standardized-problem-types>>)
* 2020-11-04
** added: <<remove-collection-items, Remove a selection of items from a collection>> (<<Collection, Collection>>)
** updated: status codes made consistent in various locations (<<Collection>>, <<Document>>, <<HTTP Methods>> and <<status-codes>>)
** added: status codes <<http-429, 429 Too Many Requests>> and  <<http-502, 502 Bad Gateway>>  (<<status-codes>>)
** added: table about how to use each HTTP method (<<HTTP Methods, HTTP Methods>>)
** added: table listing <<status-codes-by-method,acceptable status codes for each method>> (<<status-codes, Status Codes>>)
* 2020-09-09
** new: recommend use of CloudEvents specification (<<events>>)
** add guidelines on API health checks (<<health>>)
** move common OpenAPI schemas to separate GitHub repositories (<<belgif-openapi-types>>)
* 2020-08-03
** allow OpenAPI 3.0 (<<api-specs>>)
** remove unmaintained swagger-validator-maven-plugin and styleguide-validationrules from tools list (<<openapi-tools>>)
** change status codes to string types in example OpenAPI definitions to be compliant to the OpenAPI standard
** set license of this guide to Apache License, Version 2.0 (<<license,Introduction>>)
* 2020-03-24
** add links to GitHub, vocabularies and OAS schemas in the <<Introduction>>
* 2020-01-10
** updated rules: naming of <<JSON properties>> and naming of <<JSON data types>>: no digits as first letter and no dots in names
** added <<http-413,413 Payload Too Large>> to list of HTTP status codes
** updated <<Resource URI>> notation rule: no trailing slashes in URIs
** added rule: <<default-values>> in OpenAPI specification
** added <<Controller>> resource archetype and move all archetypes to <<Resources>> chapter
* 2019-05-23
** update list of standard problem types and add InvalidParamProblem schema to problem-v1.yaml, see <<Standardized problem types>>
** new rule: naming of identifiers in <<Document>>
** add status code `303 See Other` to <<create-resource, Create a new resource >>
** new rule: use tags in <<openapi,OpenAPI>>
** new section: how to specify <<media-types-openapi, media types in OpenAPI>>
** update rules: naming of <<JSON properties>> and naming of <<JSON data types>> to make names more meaningful
** new rule: use `description` and avoid `title` to describe <<JSON data types>>
** updated rule: String and integer types (<<JSON data types>>). String based codes should have a unique representation.
* 2019-01-22
** modified <<API specifications>> guidelines for reusable definitions to be put in Swagger files instead of multiple smaller JSON schema files
** gCloud JSON Schemas refactored to this new file structure
** updated list of Swagger editors and code generators in <<Tools>>
** added guidelines about <<Tracing>> with standardized HTTP headers
** add OpenAPI example of multi-valued query param to <<resources>>
** added rule: place reference data resources in `/refData` (<<doc-resource>>)
** add list of reserved resource names to <<Reserved words>>
** document `select` reserved query param to filter resource representation (<<document-consult>>)
* 2018-11-26
** add SelfLink type in <<Hypermedia controls>>
** recommend American English for <<JSON>> property names and <<JSON data types>>
** add recommendations on typing of properties in <<JSON data types>> (integer/string, enums)
* 2018-09-09
** HttpLink type updated in <<Hypermedia controls>> to be read only instead of required
** new rule in <<JSON data types>> for enum values
* 2018-08-09
** Standardized Problem response for several use cases in <<Error handling>> and updated Problem examples throughout the guide
* 2018-08-08
** added clarifications and example for use of `HttpLink` to <<Hypermedia controls>>
** changed guideline for JSON Schemas to single root type per file and add rule on common BelGov schemas
* 2018-06-29
** added files with common data types containing types referenced throughout the guide
** added MergePatch type to <<Partial update>>
** added guidelines for <<Long-running tasks>>
* 2018-05-28
** added <<Caching>> guidelines
* 2018-04-25
** added <<Internationalization (I18N)>> guidelines
** updated <<Controller>>, allowing verb as child resource and GET method in some cases
** update format of version number in <<API specifications>>
** added contact email address in <<Introduction>>
** prefix `BelGov-` added for custom <<reserved-HTTP-headers>>
* 2018-04-19
** guidelines about reusable JSON Schemas
* 2018-04-18
** added <<versioning>> guidelines
** removed collector, added "Non-CRUD operations" under <<document>> section
* 2018-03-14
** added reserved HTTP headers and rule on custom http headers (<<reserved-HTTP-headers>>)
** content negotiation and JSON subtypes added to <<Media Types>>
** <<collections-consult>>: empty items array mandatory when collection is empty
** relax the rule on `additionalProperties` to be compatible with its use for embedded resources
* 2018-03-07
** <<Error handling>>: use of RFC 7807
====
