[[health]]
== Health ==

[rule, hlth-res]
====
Each REST API SHOULD expose a `GET /health` operation which returns the current availability status of the service.

Access to this resource SHOULD be granted to any client of the API.

The payload SHOULD be a JSON object with a property `status` of type `string`, that has one of the standardized values below, or a custom value for other API-specific use cases.
It SHOULD NOT contain any implementation or infrastructure details for security reasons, unless called by a trusted privileged client.

The HTTP response status SHOULD be either `200 OK` when the service is up or partially available, or `503 Service Unavailable` when the service is down or out of service.

Clients SHOULD interpret any other HTTP 5xx status, or lack of HTTP response, as the API being unreachable.

[cols="1,1,4", options="header"]
|===
|Status|Status Code|Description
|UP| 200 |The API is functioning as expected.
|DEGRADED | 200 | The API is partly unavailable but service can be continued with reduced functionality.
|DOWN| 503 |The API is suffering unexpected failures.
|===
====

If the health checks triggered by calling `GET /health` are resource-intensive, API implementations should consider caching the result. This may also protect against denial-of-service (DoS) attacks if the operation can be called from untrusted sources.

.Service is available
====
```json
{
  "status": "UP"
}
```
====

.Service is down
====

```json
{
  "status": "DOWN"
}
```

When called by a trusted privileged client, the response may contain additional properties with detailed information.
```json
{
  "status": "DOWN",
  "details": {
    "datastore": {
      "status": "DOWN",
      "errorMessage": "connection timeout"
    }
  }
}
```
====

The health resource is specified in https://github.com/belgif/openapi-common/blob/master/src/main/openapi/common/v1/common-v1.yaml[common-v1.yaml].
Note that uppercase is used for the status values, which differs from the <<enum-rule>>, in order to align with existing health checks provided by frameworks like https://docs.spring.io/spring-boot/docs/2.3.1.RELEASE/reference/htmlsingle/#production-ready-health[Spring Boot] and https://download.eclipse.org/microprofile/microprofile-health-2.2/microprofile-health-spec.html[MicroProfile Health].
The format of additional component-level details is not specified.