== JSON

All RESTful services must support *JSON* (Javascript Object Notation https://tools.ietf.org/html/rfc7159[RFC 7159^]).


=== JSON object

For extensibility, the payload of a RESTful request or response should always be a JSON object (instead of an array, string , number, etc). This way the request or response can always be extended with new properties.

Service consumers should be aware that JSON objects can always be extended with additional JSON properties. This shouldn't break the client code. The unknown properties must be _ignored_.

=== JSON properties

[rule, jsn-naming]
.Naming of JSON properties
====
All JSON property names are in American English and are written in _lowerCamelCase_ notation.
This also applies to abbreviations part of a property name : all letters after the first one should always be lowercase.

Do not use underscores (_), hyphens (-) or dots (.) in a property name, nor use a digit as first letter.

Overly generic terms like `info(rmation)` and `data` SHOULD NOT be used as property name or as part of it.

A JSON property SHOULD refer to the business meaning of its value rather than how it is defined.

Properties used from other standards, like OpenID Connect and OAuth2, are allowed to deviate from this rule.
====

|===
|KO|OK

|SSIN | ssin
|partnerSSIN | partnerSsin
|customerInformation | customer
|descriptionString | description
|===

[subs="normal"]
```json
{
  "name": "Belgacom",
  "nssoNbr": 93017373,
  "enterprise": {
    "enterpriseNumber": "0202239951"
  }
}
```

[rule, jsn-null]
.Null values
====
Properties with a `null` value SHOULD be stripped from the JSON message.

A notable exception to this rule are JSON Merge Patch requests, in which a `null` value indicates the removal of a JSON property.

Note that this rule doesn't apply to empty values (e.g. empty strings `""` or empty arrays `[]`) as they are considered different from a `null` value.
====

|===
|*NOK*|*OK*
a|[subs="normal"]
```json
{
  "name": "Belgacom",
  "nssoNbr": 93017373,
  "enterprise": null
}
```

a|[subs="normal"]
```json
{
  "name": "Belgacom",
  "nssoNbr": 93017373
}
```
|===

**The JSON properties have no specific order inside a JSON object.**

[cols="1,1"]
|===
a|[subs="normal"]
```json
{
  "name": "Belgacom",
  "nssoNbr": 93017373
}
```


a|[subs="normal"]
```json
{
  "nssoNbr": 93017373,
  "name": "Belgacom"
}
```
|===

**Dates are written in ISO 8601 full-date format: yyyy-MM-dd**

See https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#data-types[OpenAPI 3.0 data types^] and https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 section 5.6^].

```json
{
  "birthday": "1930-07-19"
}
```

**Date/time are written in ISO 8601 date-time format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX**

See https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-7.3.1[JSON Schema Validation 7.3.1. date-time^] and https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 section 5.6^].
The fraction part for sub second precision is optional and may be of any length.

.Example UTC
```json
{
  "lastModification": "2016-04-24T09:26:01.5214Z"
}
```

.Example with timezone
```json
{
  "lastModification": "2016-04-24T11:26:00+02:00"
}
```
