== Tracing

In order to uniquely identify requests or response messages, a tracing ID may be added as HTTP header.
This tracing id can be used to be able to trace the flow of calls across APIs and organizations.

The trace ID could be used for example:

* for operational purposes, to enable lookup related technical logs
* for audit logging, in order to be able to trace the origin of each request.
  It may be a legal requirement to have such audit logging when sensitive data is exchanged.

[rule, trc-header]
.HTTP headers for tracing
====
APIs exposed to third parties SHOULD support the tracing HTTP header `BelGov-Trace-Id` on both requests and responses.
Generated trace IDs MUST NOT be longer than 36 characters and unique.
The trace id on a response MUST be generated by the API provider and is not copied from the request.
Using UUIDs as tracing headers is RECOMMENDED.

Additionally, the `BelGov-Related-Trace-Id` HTTP header MAY be present on a response.
Its value MUST be the same as the `BelGov-Trace-Id` on the request.

The `BelGov-Trace-Id` value on every outgoing call SHOULD be unique, even when they are made within a single context e.g. as part of handling a single incoming request. However for security reasons, an API provider SHOULD NOT depend on an external client to generate a correct unique value.
When auditing functionality is needed, it SHOULD be possible to correlate the various tracing IDs used in the context of a request.
====

[rule, trace-w3c]
.W3C headers for tracing and context
====
Within an organization's trust boundary (i.e. internal calls), alternative HTTP headers MAY be used to trace calls.

The standardized https://w3c.github.io/trace-context/[W3C Trace Context] and https://w3c.github.io/baggage/[baggage] headers are RECOMMENDED, which are compatible with the https://opentelemetry.io/docs/specs/otel/[OpenTelemetry specification].

OpenTelemetry, also known as OTel, is a vendor-neutral open source observability framework for instrumenting, generating, collecting, and exporting telemetry data such as traces, metrics, and logs across heterogeneous platforms.

A trace context allows tracing tools to follow, analyze and debug a transaction across multiple software components. Baggage can be used, among other things, to annotate telemetry, adding contextual information to metrics, traces, and logs.

APIs MAY support both W3C and `BelGov(-Related)-Trace-Id` headers dynamically depending on the client being located within the trust boundary or not.
====

When crossing a trust boundary, a mapping can be made, for instance:

* the client's `BelGov-Trace-Id` can be put on the baggage of internal calls
* the `BelGov-Trace-Id` of outgoing messages can be set to the OpenTelemetry `trace-id` or `span-id`

For calls across trust boundaries (e.g. by a 3rd party client), the W3C headers are not being recommended because they are less designed for this use case:

* trace information wouldn't be complete, missing trace parts at external parties
* measures have to be taken to address security concerns (Denial of Service, information exposure): verify and filter input values, restart the trace, filter sensitive information in outgoing headers (e.g. in baggage or tracestate)
** also see "Security Considerations" and "Privacy Considerations" in https://w3c.github.io/trace-context/#security-considerations[W3C Trace Context] and https://w3c.github.io/baggage/#security-considerations[baggage]
* W3C tracing and baggage headers are hard to implement (trace-id, parent-id, flags, tracestate) for parties that aren't using an OpenTelemetry implementation

