== Tracing

In order to uniquely identify requests or response messages, a tracing ID may be added as HTTP header.
This tracing id can be used to be able to trace the flow of calls across APIs and organizations.

The trace ID could be used for example:

* for operational purposes, to enable lookup related technical logs
* for audit logging, in order to be able to trace the origin of each request.
  It may be a legal requirement to have such audit logging when sensitive data is exchanged.

[rule, trc-header]
.HTTP headers for tracing
====
APIs SHOULD support the tracing HTTP header `BelGov-Trace-Id` on both requests and responses.
Generated trace IDs MUST NOT be longer than 36 characters and unique.
The trace id on a response MUST be generated by the API provider and is not copied from the request.
Using UUIDs as tracing headers is RECOMMENDED.

Additionally, the `BelGov-Related-Trace-Id` HTTP header MAY be present on a response.
Its value MUST be the same as the `BelGov-Trace-Id` on the request.

Within an organization, other headers MAY be used for tracing calls, for instance the headers supported by tracing tools like Zipkin or Jaeger.
====

In communication external to an organization, each `BelGov-Trace-Id` value should be unique.
For instance, when a RESTful service makes multiple outgoing calls within the context of the same incoming request, every outgoing request should be uniquely identifiable with its own ID.
For auditing purposes, it should be possible to correlate the various tracing IDs used in the context of a request.

An API provider should not be dependent on the client generating correct unique trace IDs.
