= Links

Thanks to links (_hypermedia controls_) a client can navigate through the REST API without hardcoding URIs to specific resources. It suffices to know a limited set of entry points and navigate to the desired information. This adds _flexibility_ to the evolution of the API and increases _loose coupling_ between client and server.

[rule, hyp-links]
.Links to self and other resources
====
When referencing another resource within the same API, a link SHOULD be added using the `href` attribute.

It is NOT RECOMMENDED to link to resources in other APIs to avoid a tight coupling between the APIs, unless the link target is guaranteed to remain very stable (like the `href` links to standard problem types xref:errorhandling.adoc#rule-err-problem[[err-problem\]]).

Entities with a sensitive identifier don't have their own URI (see xref:resources.adoc#rule-sens-dat[[sens-dat\]]), so they don't need to be linked.

Each resource MAY also contain its own location in a `self` attribute at root level of the JSON document.

URIs SHOULD always be absolute.
====

CAUTION: For brevity, most URIs in the style guide examples are shortened, but in reality URIs should always be absolute.

All `href` hyperlinks are derived from this minimal link type:

.HttpLink JSON schema (from https://github.com/belgif/openapi-common/blob/master/src/main/openapi/common/v1/common-v1.yaml[common-v1.yaml])
```YAML
HttpLink:
  description: A base type of objects representing links to resources.
  type: object
  properties:
    href:
      description: Any absolute URI that is using http or https protocol
      type: string
      format: uri
      readOnly: true
```

`self` hyperlinks are derived from the following type:

.SelfLink JSON schema (from https://github.com/belgif/openapi-common/blob/master/src/main/openapi/common/v1/common-v1.yaml[common-v1.yaml])
```YAML
SelfLink:
  description: A base type representing a link to the resource's own location within its representation
  type: object
  properties:
    self:
      description: Absolute URI (http or https) to the the resource's own location.
      type: string
      format: uri
      readOnly: true
```

Links should not be used in request bodies in a PUT, POST or PATCH context, as indicated by the `readOnly: true` property.
In a JSON response, they can be added anywhere.

.Resource links
====
GET pass:attributes[{API}/organizations/0202239951]

[subs="+attributes"]
```json
{
  "self": "{API}/organizations/0202239951"
  "succeededBy": {
    "enterpriseNumber": "0123456789",
    "href": "{API}/organizations/0123456789"
  },
  "owner": "12345678902",
  "website": "https://wwww.myenterprise.com"
}
```

The `href` in `succeededBy` is a link to the corresponding organization's document resource, while `owner` is a sensitive identifier and therefore has no link.

PATCH pass:attributes[{API}/organizations/0202239951]

[subs="+attributes"]
```json
{
  "succeededBy": {
    "enterpriseNumber": "0123456789",
  },
  "owner": {
    "ssin": "12345678902"
  },
  "website": "https://wwww.mynewwebsite.com"
}
```

The corresponding JSON schema includes the link types using `allOf`.
As `website` isn't a reference to another API resource, it is not defined using the `HttpLink` type.

```YAML
components:
  schemas:
    Enterprise:
      allOf:
      - "$ref": "./common/v1/common-v1.yaml#/components/schemas/SelfLink"
      - type: object
        properties:
          owner:
            "$ref": "#/components/schemas/PersonReference"
          website:
            type: string
            format: uri
    PersonReference:
      allOf:
        - "$ref": "./common/v1/common-v1.yaml#/components/schemas/HttpLink"
        - type: object
          properties:
            ssin:
              "$ref": "./person-identifier/v1/person-identifier-v1.yaml#/components/schemas/Ssin"
```
====

Hyperlinks for xref:resources-collection.adoc#pagination[Pagination] inside collections and self-references should use a simple URI value in combination with their corresponding link relations (next, prev, first, last, self) instead of the extensible link type.

[[collection-links]]
.Pagination links
====
[subs="+attributes"]
```json
{
   "self": "{API}/organizations?page=2&pageSize=10",
   "prev": "{API}/organizations?page=2&pageSize=1",
   "next": "{API}/organizations?page=2&pageSize=3"
}
```
====

The use of https://tools.ietf.org/html/rfc5988[Web Linking] and https://tools.ietf.org/html/draft-kelly-json-hal-08[Hypertext Application Language (HAL)] is not recommended.
