= HTTP Methods

== GET
**GET should be used to retrieve a representation of a resource and may be used to execute an idempotent xref:resources-controller.adoc#controller[controller] operation without side-effects.** It is a strict read-only method, which should never modify the state of the resource.

== POST
*POST should be used to xref:resources-collection.adoc#create-resource[create a new resource] in a collection, to execute a xref:resources-controller.adoc#controller[controller] resource or as alternative for operations with xref:resources.adoc#rule-sens-dat[sensitive input data].*

When using for resource creation, the POST request’s body contains the suggested state representation of the new resource to be added to the server-owned collection. The response should contain a Location HTTP header containing the URI of the newly created resource, while the body contains either its (partial or full) representation or is empty.

POST operations may have side effects (i.e. modify state), and are not required to be idempotent.

== PUT
**PUT should be used to update a stored resource under a consumer supplied URI.** It could be used to insert a new resource in case the client application decides on the resource identifier.

If the URI refers to an already existing resource, the enclosed entity SHOULD be considered as a new version to replace the one residing on the server. If the target resource is successfully modified in accordance with the state of the enclosed representation, then a 200 (OK) response SHOULD be sent to indicate successful completion of the request.

If the URI does not point to an existing resource, and that URI is capable of being defined as a new resource, the server can create the resource with that URI. The server MUST inform the client by sending a 201 (Created) response to indicate successful creation.

PUT operations may have side effects (i.e. modify state), but MUST be idempotent.


== PATCH
*PATCH should be used to update partially a representation of a resource.*

The enclosed entity contains a set of instructions describing how a resource currently residing on the origin server should be modified to produce a new version.
The PATCH method affects the resource identified by the Request-URI, and it also MAY have side effects on other resources; i.e., new resources may be created, or existing ones modified, by the application of a PATCH.
PATCH operations are not required to be idempotent, however they will often be in practice.

See xref:resources-document.adoc#document-partial-update[Partial update] on how to specify the set of instructions describing how a resource on the server should be modified.


**Compatibility**

The PATCH http method may not be supported in all components participating in the communication (e.g. HTTP client, intermediary proxy).
If these can't be upgraded to add support, client and server may agree to work around this by implementing PATCH as POST operations with HTTP header 'X-HTTP-Method-Override: PATCH'.

== DELETE
*DELETE should be used to remove a resource from its parent.* Once a DELETE request has been processed for a given resource, the resource can no longer be found by clients. Therefore, any future attempt to retrieve the resource’s state representation, using either GET or HEAD, must result in a 404 (“Not Found”)​ status returned by the API.

== HEAD
**HEAD should be used to only retrieve the HTTP response headers​.** HEAD returns the same response as GET, except that the API returns an empty body. It is strictly read-only.

== OPTIONS
OPTIONS should be used to retrieve metadata that describes a resource’s available interactions.

 


