= Collection

A collection resource is a server-managed list of document resources.

[rule, col-name]
.Collection name
====
A plural noun SHOULD be used for collection names, for example 'employers' or 'children'.
====

.Collection name
====
{API}/employers[^] - a collection of employers

{API}/persons/children[^] - a collection of children as a child resource of a person. The person identifier of the parent is omitted from the path, because it is considered sensitive.
====

[[collections-consult, Searching a collection]]
== Search

[rule, col-get]
.API operation to search a collection
====
An operation to search a collection resource SHOULD be provided as a `GET` method on the collection resource URI.

When searching requires input parameters with a complex structure (e.g. extensive filter or sorting parameters) or when the input contains sensitive data, a `POST` operation on a `/search` controller MAY be used instead of `GET`. This allows to represent the input parameters in a structured manner in a JSON request body without the limitations or exposure of query parameters.
Any <<Pagination, pagination>> input parameters SHOULD still be included as query parameters, allowing to re-send the same payload to retrieve the next page of results.
====

The recently introduced HTTP method `QUERY`, providing an alternative to a `/search` controller, SHOULD NOT be used yet (xref:methods.adoc#rule-meth-http[[meth-http\]]).

[rule, col-repres]
.Representation of a collection
====
The representation of a collection MUST contain a list of links to child resources:

* A collection result MUST contain an `items` property with an array of objects, each one representing an item in the collection.
* In these objects, a `href` property MUST be present with a link to the resource.
* The unique business identifier SHOULD be present for each item.
* Each item object MAY be extended with some key business properties, needed for display in a master view.
* In case the collection is empty, the `items` property MUST have an empty array as value.
* The `title` property  MAY be used to provide a human-readable description for an item, usable as display text for the link.
* The number of items in the collection result set MAY be included in the response using the `total` property. If the response is paginated, its value MUST correspond to the number of items regardless of pagination, rather than only the number of items in the current page.
====

CAUTION: A collection resource, like other resources, MUST always return a JSON object as top-level data structure to support extensibility (xref:versioning.adoc#rule-evo-object[[evo-object\]]). Do not return a JSON array, because the moment you like to add paging, hypermedia links, etc. your API will break.

.Consulting a collection
====

[subs=normal]
----
GET {API}/employers?title=P*[^] HTTP/1.1
----

[cols="1,2,3"]
|===
3+|Request
|xref:methods.adoc#get[GET]
|/employers/+{employerId}+
|List employers

|parameters
|filtering, sorting or pagination parameters
|see <<rule-col-sort>>, <<searching, searching>> and <<Pagination, pagination>>

3+| Response

|body
2+a|
[source,json,subs="normal"]
----
{
 "items":[
   {
     "href":"{API}/employers/93017373[/employers/93017373^]",
     "title":"Proximus",
     "employerId": 93017373,
     "enterpriseNumber": "0202239951"
   },
   {
     "href":"{API}/employers/20620259[/employers/20620259^]",
     "title":"Partena VZW",
     "employerId": 20620259,
     "enterpriseNumber": "0409536968"
   }
 ],
 "total":2
}
----
3+|Most used response codes
| xref:statuscodes.adoc#http-200[200] | OK | Default response code, also when the collection is empty.
| xref:statuscodes.adoc#http-400[400] | Bad Request | Generic error on client side. For example, the syntax of the request is invalid.
| xref:statuscodes.adoc#http-404[404] | Not found | The URI provided cannot be mapped to a resource.
|===

WARNING: xref:statuscodes.adoc#http-204[204 No content]  should not be used when consulting a collection.

OpenAPI schemas for the response payload:

[source, yaml]
----
EmployersCollection:
  type: object
  properties:
    items:
      type: array
      items:
        $ref: "#/components/schemas/EmployerLink"
    total:
      type: integer
  required:
    - items
    - total
EmployerLink:
  allOf:
  - $ref: common/v1/common-v1.yaml#/components/schemas/HttpLink
  - type: object
    properties:
      employerId:
        $ref: "./employer/identifier/v1/employer-identifier-v1.yaml#/components/schemas/EmployerId"
      enterpriseNumber:
        $ref: "./organization/identifier/v1/organization-identifier-v1.yaml#/components/schemas/EnterpriseNumber"
----
====


.Consultation with complex or sensitive input
====

If input with a complex structure is needed, or its input may contain sensitive data, a `/search` controller with `POST` may be used.

.Request
----
POST {API}/employers/search
----

[source,json]
----
{
  "title": [
    {
      "excludeIfMatching": false,
      "expression": "P*"
    },
    {
      "excludeIfMatching": true,
      "expression": "B*"
    }
  ]
}
----

.Response

The response is the same as for the `GET` alternative.
====

[rule,col-embed]
.Getting full representations of collection items
====
When the collection items contain few data, you may want to retrieve them in full when getting the collection.
In this case, the full representations MUST be included in an 'embedded' property as described in xref:performance.adoc#embedding[Embedding resources].
====

.Consulting a collection with embedded items
====
[subs=normal]
```
GET {API}/appendices/employerclasses?embed=items[^] HTTP/1.1​
```

.Response
[subs=normal]
```JSON
{
 "items": [
  {
   "value": "0",
   "href": "{API}/appendices/employerclasses/0"
  }, {
   "value": "2",
   "href": "{API}/appendices/employerclasses/2"
  }
 ],
 "total":2,
 "embedded": {
   "{API}/appendices/employerclasses/2[/appendices/employerclasses/2^]": {
     "value": "2",
     "description": {
       "nl": "Bijzondere categorie voor werkgevers die voor hun arbeiders een speciale bijdrage verschuldigd zijn.",
       "fr": "Catégorie particulière pour les employeurs redevables pour les ouvriers d'une cotisation spéciale."
      }
   },
   "{API}/appendices/employerclasses/0[/appendices/employerclasses/0^]": {
     "value": "0",
     "description": {
      "nl": "Algemene categorie voor werkgevers van commerciële of niet-commerciële aard.",
      "fr": "Catégorie générale pour les employeurs, de type commercial ou non-commercial."
     }
   }
 }
}
```

.JSON schemas
```YAML
AppendixCodesCollection:
  description: A collection of appendix codes
  type: object
  properties:
    items:
      type: array
      items:
        $ref: '#/components/schemas/AppendixCodeLink'
    total:
      type: integer
    embedded:
      type: object
      additionalProperties:
        $ref: 'appendixCode.yaml#/components/schemas/AppendixCode'
  required:
    - items
    - total
AppendixCodeLink:
  allOf:
  - $ref: 'common/v1/common-v1.yaml#/components/schemas/HttpLink'
  - type: object
    properties:
      value:
        $ref: 'appendixCode.yaml#/components/schemas/AppendixCodeValue'
```
====

[[sorting]]
=== Sorting

[rule, col-sort]
.Sorting a collection
====
A `sort` multi-value query parameter MAY be provided to allow a client to sort the items of a collection resource on one or more specified properties.
Descending sorting order can be indicated by prefixing the property name with `-`.

The API SHOULD document which properties can be used for sorting, and whether descending order is allowed.

In case a `/search` controller is used, the sorting parameters should be represented in a structured manner in the request body, instead of using query parameters. Separate parameters for sorting properties and sorting order can be used then.
====

.Sort query parameter
[cols="3*"]
|===
| sort
| Multi-value query param with list of properties to sort on.
Direction is ascending by default. To indicate descending, prefix property with `-`.
|`?sort=age&sort=-name`
|===

[[filtering]]
== Filtering

[rule, col-filter]
.Filtering items in a collection
====
A collection may support xref:reserved.adoc#query-parameters[query parameters] to filter its items:

* a query parameter with the name of a document property, filters items on the specified value
* the query parameter `q` is reserved for a full text search on all the document's content
* other filter parameters may be supported, e.g. to look up items within a search period

Unless the API documentation explicitly states otherwise, returned collection items:

* should satisfy ALL filter query parameters (AND-logic)
* have to match ANY of the values of a multi-valued filter query parameter (OR-logic).
====

For example, the query 
`GET /cars?doors=5&color=black&color=blue` should be interpreted by default as: "search for all cars that have 5 doors AND are of color blue OR black".

.Searching in a collection
====
[subs=normal]
```
GET {API}/enterprises?title=P*[^] HTTP/1.1
```

[cols="1,2,3"]
|===
|xref:methods.adoc#get[GET]
|/organizations
|get all the organization documents in the collection


3+|Parameters

|name
|query-param
|Only match organizations that have a specific name.

3+|Response

|body
a|
a|
[source,json, subs=normal]
----
{
  "items": [
    {
      "href": "{API}/organizations/0202239951",
      "name": "Proximus",
      "enterpriseNumber": "0202239951"
    },
    {
      "href": "{API}/organizations/0816851945",
      "name": "Partena",
      "enterpriseNumber": "0816851945"
    }
  ],
  "total": 2
}
----

3+|Most used response codes
|xref:statuscodes.adoc#http-200[200]
|OK
|Default response code, also when filtered collection is empty.
| xref:statuscodes.adoc#http-400[400] | Bad Request | Generic error on client side. For example, the syntax of the request is invalid.
| xref:statuscodes.adoc#http-404[404] | Not found | The URI provided cannot be mapped to a resource.
|===

WARNING: xref:statuscodes.adoc#http-204[204 No content] should not be used with GET.
====

== [[Pagination]] [[pagination]] Pagination

[rule, col-paging]
.Paging over a large collection
====
Collection with too many items MUST support pagination.
There are two pagination techniques:

* offset-based pagination: numeric offset identifies a page
* cursor-based (aka key-based or luke index): a unique key element identifies a page

Cursor-based pagination has some advantages, especially for high volumes.
Take into account the considerations http://zalando.github.io/restful-api-guidelines/#160[listed in the Zalando API guidelines] before choosing a pagination technique.
====

.Reserved JSON properties for pagination
|===
|`next` | MANDATORY (except for the last page) | hyperlink to the next page

|`next` | REQUIRED (except for the last page) | hyperlink to the next page
|`prev` | OPTIONAL | hyperlink to the previous page
|`pageSize` | RECOMMENDED | Maximum number of items per page. For the last page, its value should be independent of the number of actually returned items.
| `page` |REQUIRED (offset-based); N/A (cursor-based) | index of the current page of items, should be 1-based (the default and first page is 1)
| `first` | OPTIONAL | hyperlink to the first page
| `last` | OPTIONAL | hyperlink to the last page
| `total` | OPTIONAL | Total number of items across all pages. If filter parameters are used, this is the total of the result set after filtering, not of the entire collection.
|===

The names of the properties with hyperlink values and the `items` property are derived from the https://www.iana.org/assignments/link-relations/link-relations.xml[IANA registered link relations].

.Reserved query parameters for pagination
|===
| `pageSize` | OPTIONAL |  maximum number of items per page desired by client; must have a default value if absent.
| `page` | REQUIRED with default value 1 (offset-based); N/A (cursor-based) | the index of page to be retrieved

|===

A reusable `PageQueryParameter` OpenAPI component is defined in https://github.com/belgif/openapi-common/blob/main/src/main/openapi/common/v1/common-v1.yaml#L36[common-v1.yaml]. Examples of other OpenAPI components for pagination can be found https://github.com/belgif/openapi-common/blob/main/src/test/openapi/Pagination.yaml[here], but should be modified according to which pagination parameters, size limits and default values are supported by your API.

.Offset-based pagination
====
[subs="normal"]
```
GET {API}/organizations?page=2&pageSize=2 HTTP/1.1
```

[source,json, subs="normal"]
----
{
  "self": "{API}/organizations?page=2&pageSize=2",
  "items": [
    {
      "href": "{API}/organizations/0202239951",
      "title": "Proximus",
      "enterpriseNumber": "0202239951"
    },
    {
      "href": "{API}/organizations/0212165526",
      "title": "CPAS de Silly",
      "enterpriseNumber": "0212165526"
    }
  ],
  "pageSize": 2,
  "page": 2,
  "total": 7,
  "first": "{API}/organizations?pageSize=2",
  "last": "{API}/organizations?page=4&pageSize=2",
  "prev": "{API}/organizations?page=1&pageSize=2",
  "next": "{API}/organizations?page=3&pageSize=2"
}
----
====

.Cursor-based pagination
====
[subs="normal"]
```
GET {API}/organizations?after=0244640631[^] HTTP/1.1
```

[source,json, subs="normal"]
----
{
  "self": "{API}/organizations?afterEnterprise=0244640631&pageSize=2[/organizations?after=0244640631&pageSize=2^]",
  "items": [
    {
      "href": "{API}/organizations/0202239951[/organizations/0202239951^]",
      "title": "Proximus"
    },
    {
      "href": "{API}/organizations/0212165526[/organizations/0212165526^]",
      "title": "CPAS de Silly"
    }
  ],
  "pageSize": 2,
  "total": 7,
  "first": "{API}/organizations?pageSize=2[/organizations?pageSize=2^]",
  "next": "{API}/organizations?after=0212165526&pageSize=2[/organizations?after=0212165526&pageSize=2^]"
}
----
====

[[create-resource]]
== Create a new resource
The collection resource can be used to create new document resources from the `POST` request body.
Absent optional values are set to their default value if one is specified in the OpenAPI description.

[cols="1,2,3"]
|===
|xref:methods.adoc#post[POST]
|/employers
|create a new employer in the collection


3+|Request
|body
|​The data of the resource to create.
a|
[source,json]
----
{
  "name": "Belgacom",
  "employerId": 93017373,
  "enterprise": {
    "enterpriseNumber": "0202239951"
  }
}
----

3+|Response headers

|Location
|http-header
|The URI of the newly created resource e.g. /employers/93017373

3+|Response

|body
|
a|The API should specify for each creation operation, if it returns:

* an empty body,
* a partial resource representation (e.g. only a generated resource identifier),
* or a full resource representation.

3+|Most used response codes

|xref:statuscodes.adoc#http-201[201]
|Created
|Default response code if the resource is created. 
|xref:statuscodes.adoc#http-409[409]
|Conflict
|The resource could not be created because the request is in conflict with data on the server. E.g. the resource already exists (duplicate key violation).

|xref:statuscodes.adoc#http-303[303]
|See Other
| The resource already exists.
  May be returned instead of `409 Conflict` if it is considered a normal use case to perform the operation for an already existing resource.
  The `Location` header refers to the resource.

|===

WARNING: ​xref:statuscodes.adoc#http-200[200 OK]  should not be used with POST for creating resources.

[source]
----
POST /employers HTTP/1.1

HTTP/1.1 201 Created
Location: /employers/93017373
Content-Length: 0
Date: Wed, 06 Jan 2016 15:37:16 GMT
----

[[remove-collection-items]]
== Remove

A selection of items can be removed from a collection using the DELETE method. In fact, the collection itself cannot be removed, but it can be emptied if all its items are removed.
By using query parameters, the items to be removed can be filtered.
In order to remove a single specific item from a collection, use xref:resources-document.adoc#remove-document[ DELETE on the document resource].

[cols="1,2,3"]
|===
|xref:methods.adoc#delete[DELETE]
|/employers
|Delete all the employers documents in the collection.


3+|Parameters

|name
|query-param
|Remove only employers that have a specific name.

3+|Response

|body
|
|Empty or a message indicating success.


3+|Most used response codes
|xref:statuscodes.adoc#http-200[200]
|OK
|The items are successfully removed from the collection and returned.
|xref:statuscodes.adoc#http-204[204]
|No content
| The items are successfully removed from the collection but no additional content is included in the response body.
| xref:statuscodes.adoc#http-400[400] | Bad Request | Generic error on client side. For example, the syntax of the request is invalid.
| xref:statuscodes.adoc#http-404[404] | Not found | The collection resource does not exist and thus cannot be deleted.
|===
